/*
 * generated by Xtext
 */
package org.xtext.unq.planificador.ui.contentassist

import org.xtext.unq.planificador.ui.contentassist.AbstractPdmProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PdmProposalProvider extends AbstractPdmProposalProvider {
}
