/*
* generated by Xtext
*/
package org.xtext.unq.planificador.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class PdmGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportsImportParserRuleCall_0_0 = (RuleCall)cImportsAssignment_0.eContents().get(0);
		private final Assignment cProfesorsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cProfesorsProfesorParserRuleCall_1_0 = (RuleCall)cProfesorsAssignment_1.eContents().get(0);
		private final Assignment cHorasAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cHorasHoraParserRuleCall_2_0 = (RuleCall)cHorasAssignment_2.eContents().get(0);
		private final Assignment cMateriasAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMateriasMateriaParserRuleCall_3_0 = (RuleCall)cMateriasAssignment_3.eContents().get(0);
		private final Assignment cAulasAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAulasAulaParserRuleCall_4_0 = (RuleCall)cAulasAssignment_4.eContents().get(0);
		private final Assignment cCargasHorariasAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cCargasHorariasCargaHorariaParserRuleCall_5_0 = (RuleCall)cCargasHorariasAssignment_5.eContents().get(0);
		private final Assignment cCargasHorariasDocentesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCargasHorariasDocentesCargaHorariaDocenteParserRuleCall_6_0 = (RuleCall)cCargasHorariasDocentesAssignment_6.eContents().get(0);
		private final Assignment cHorariosAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cHorariosHorariosParserRuleCall_7_0 = (RuleCall)cHorariosAssignment_7.eContents().get(0);
		private final Assignment cDiasAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDiasDiaParserRuleCall_8_0 = (RuleCall)cDiasAssignment_8.eContents().get(0);
		private final Assignment cSemestreAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cSemestreSemestreParserRuleCall_9_0 = (RuleCall)cSemestreAssignment_9.eContents().get(0);
		private final Assignment cPlanificacionesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cPlanificacionesPlanificacionParserRuleCall_10_0 = (RuleCall)cPlanificacionesAssignment_10.eContents().get(0);
		private final Assignment cHorariosAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cHorariosHorarioParserRuleCall_11_0 = (RuleCall)cHorariosAssignment_11.eContents().get(0);
		private final Assignment cRecursosAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cRecursosRecursoParserRuleCall_12_0 = (RuleCall)cRecursosAssignment_12.eContents().get(0);
		
		//Model:
		//	imports+=Import* profesors+=Profesor* horas+=Hora* materias+=Materia* aulas+=Aula* cargasHorarias+=CargaHoraria*
		//	cargasHorariasDocentes+=CargaHorariaDocente* horarios+=Horarios* dias+=Dia* semestre+=Semestre*
		//	planificaciones+=Planificacion* horarios+=Horario* recursos+=Recurso*;
		public ParserRule getRule() { return rule; }

		//imports+=Import* profesors+=Profesor* horas+=Hora* materias+=Materia* aulas+=Aula* cargasHorarias+=CargaHoraria*
		//cargasHorariasDocentes+=CargaHorariaDocente* horarios+=Horarios* dias+=Dia* semestre+=Semestre*
		//planificaciones+=Planificacion* horarios+=Horario* recursos+=Recurso*
		public Group getGroup() { return cGroup; }

		//imports+=Import*
		public Assignment getImportsAssignment_0() { return cImportsAssignment_0; }

		//Import
		public RuleCall getImportsImportParserRuleCall_0_0() { return cImportsImportParserRuleCall_0_0; }

		//profesors+=Profesor*
		public Assignment getProfesorsAssignment_1() { return cProfesorsAssignment_1; }

		//Profesor
		public RuleCall getProfesorsProfesorParserRuleCall_1_0() { return cProfesorsProfesorParserRuleCall_1_0; }

		//horas+=Hora*
		public Assignment getHorasAssignment_2() { return cHorasAssignment_2; }

		//Hora
		public RuleCall getHorasHoraParserRuleCall_2_0() { return cHorasHoraParserRuleCall_2_0; }

		//materias+=Materia*
		public Assignment getMateriasAssignment_3() { return cMateriasAssignment_3; }

		//Materia
		public RuleCall getMateriasMateriaParserRuleCall_3_0() { return cMateriasMateriaParserRuleCall_3_0; }

		//aulas+=Aula*
		public Assignment getAulasAssignment_4() { return cAulasAssignment_4; }

		//Aula
		public RuleCall getAulasAulaParserRuleCall_4_0() { return cAulasAulaParserRuleCall_4_0; }

		//cargasHorarias+=CargaHoraria*
		public Assignment getCargasHorariasAssignment_5() { return cCargasHorariasAssignment_5; }

		//CargaHoraria
		public RuleCall getCargasHorariasCargaHorariaParserRuleCall_5_0() { return cCargasHorariasCargaHorariaParserRuleCall_5_0; }

		//cargasHorariasDocentes+=CargaHorariaDocente*
		public Assignment getCargasHorariasDocentesAssignment_6() { return cCargasHorariasDocentesAssignment_6; }

		//CargaHorariaDocente
		public RuleCall getCargasHorariasDocentesCargaHorariaDocenteParserRuleCall_6_0() { return cCargasHorariasDocentesCargaHorariaDocenteParserRuleCall_6_0; }

		//horarios+=Horarios*
		public Assignment getHorariosAssignment_7() { return cHorariosAssignment_7; }

		//Horarios
		public RuleCall getHorariosHorariosParserRuleCall_7_0() { return cHorariosHorariosParserRuleCall_7_0; }

		//dias+=Dia*
		public Assignment getDiasAssignment_8() { return cDiasAssignment_8; }

		//Dia
		public RuleCall getDiasDiaParserRuleCall_8_0() { return cDiasDiaParserRuleCall_8_0; }

		//semestre+=Semestre*
		public Assignment getSemestreAssignment_9() { return cSemestreAssignment_9; }

		//Semestre
		public RuleCall getSemestreSemestreParserRuleCall_9_0() { return cSemestreSemestreParserRuleCall_9_0; }

		//planificaciones+=Planificacion*
		public Assignment getPlanificacionesAssignment_10() { return cPlanificacionesAssignment_10; }

		//Planificacion
		public RuleCall getPlanificacionesPlanificacionParserRuleCall_10_0() { return cPlanificacionesPlanificacionParserRuleCall_10_0; }

		//horarios+=Horario*
		public Assignment getHorariosAssignment_11() { return cHorariosAssignment_11; }

		//Horario
		public RuleCall getHorariosHorarioParserRuleCall_11_0() { return cHorariosHorarioParserRuleCall_11_0; }

		//recursos+=Recurso*
		public Assignment getRecursosAssignment_12() { return cRecursosAssignment_12; }

		//Recurso
		public RuleCall getRecursosRecursoParserRuleCall_12_0() { return cRecursosRecursoParserRuleCall_12_0; }
	}

	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceImportedFQNParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		////recursosDeMaterias+=RecursoMateria*
		//Import:
		//	"import" importedNamespace=ImportedFQN;
		public ParserRule getRule() { return rule; }

		//"import" importedNamespace=ImportedFQN
		public Group getGroup() { return cGroup; }

		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//importedNamespace=ImportedFQN
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }

		//ImportedFQN
		public RuleCall getImportedNamespaceImportedFQNParserRuleCall_1_0() { return cImportedNamespaceImportedFQNParserRuleCall_1_0; }
	}

	public class ImportedFQNElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ImportedFQN");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cFQNParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ImportedFQN:
		//	FQN ".*"?;
		public ParserRule getRule() { return rule; }

		//FQN ".*"?
		public Group getGroup() { return cGroup; }

		//FQN
		public RuleCall getFQNParserRuleCall_0() { return cFQNParserRuleCall_0; }

		//".*"?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}

	public class FQNElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FQN");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//FQN:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class ProfesorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Profesor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProfesorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cDedicacionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDedicacionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDedicacionDedicacionParserRuleCall_3_0 = (RuleCall)cDedicacionAssignment_3.eContents().get(0);
		
		//Profesor:
		//	"profesor" name=ID "dedicacion" dedicacion=Dedicacion;
		public ParserRule getRule() { return rule; }

		//"profesor" name=ID "dedicacion" dedicacion=Dedicacion
		public Group getGroup() { return cGroup; }

		//"profesor"
		public Keyword getProfesorKeyword_0() { return cProfesorKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"dedicacion"
		public Keyword getDedicacionKeyword_2() { return cDedicacionKeyword_2; }

		//dedicacion=Dedicacion
		public Assignment getDedicacionAssignment_3() { return cDedicacionAssignment_3; }

		//Dedicacion
		public RuleCall getDedicacionDedicacionParserRuleCall_3_0() { return cDedicacionDedicacionParserRuleCall_3_0; }
	}

	public class HoraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Hora");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHoraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHoraAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHoraINTTerminalRuleCall_1_0 = (RuleCall)cHoraAssignment_1.eContents().get(0);
		
		//Hora:
		//	"hora" hora=INT;
		public ParserRule getRule() { return rule; }

		//"hora" hora=INT
		public Group getGroup() { return cGroup; }

		//"hora"
		public Keyword getHoraKeyword_0() { return cHoraKeyword_0; }

		//hora=INT
		public Assignment getHoraAssignment_1() { return cHoraAssignment_1; }

		//INT
		public RuleCall getHoraINTTerminalRuleCall_1_0() { return cHoraINTTerminalRuleCall_1_0; }
	}

	public class DedicacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Dedicacion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSIMPLEParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSEMIParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cEXCLUSIVAParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Dedicacion:
		//	SIMPLE | SEMI | EXCLUSIVA;
		public ParserRule getRule() { return rule; }

		//SIMPLE | SEMI | EXCLUSIVA
		public Alternatives getAlternatives() { return cAlternatives; }

		//SIMPLE
		public RuleCall getSIMPLEParserRuleCall_0() { return cSIMPLEParserRuleCall_0; }

		//SEMI
		public RuleCall getSEMIParserRuleCall_1() { return cSEMIParserRuleCall_1; }

		//EXCLUSIVA
		public RuleCall getEXCLUSIVAParserRuleCall_2() { return cEXCLUSIVAParserRuleCall_2; }
	}

	public class SIMPLEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SIMPLE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSIMPLEAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSimpleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//SIMPLE:
		//	{SIMPLE} "simple";
		public ParserRule getRule() { return rule; }

		//{SIMPLE} "simple"
		public Group getGroup() { return cGroup; }

		//{SIMPLE}
		public Action getSIMPLEAction_0() { return cSIMPLEAction_0; }

		//"simple"
		public Keyword getSimpleKeyword_1() { return cSimpleKeyword_1; }
	}

	public class SEMIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SEMI");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSEMIAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSemiKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//SEMI:
		//	{SEMI} "semi";
		public ParserRule getRule() { return rule; }

		//{SEMI} "semi"
		public Group getGroup() { return cGroup; }

		//{SEMI}
		public Action getSEMIAction_0() { return cSEMIAction_0; }

		//"semi"
		public Keyword getSemiKeyword_1() { return cSemiKeyword_1; }
	}

	public class EXCLUSIVAElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EXCLUSIVA");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEXCLUSIVAAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExclusivaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//EXCLUSIVA:
		//	{EXCLUSIVA} "exclusiva";
		public ParserRule getRule() { return rule; }

		//{EXCLUSIVA} "exclusiva"
		public Group getGroup() { return cGroup; }

		//{EXCLUSIVA}
		public Action getEXCLUSIVAAction_0() { return cEXCLUSIVAAction_0; }

		//"exclusiva"
		public Keyword getExclusivaKeyword_1() { return cExclusivaKeyword_1; }
	}

	public class MateriaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Materia");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMateriaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cConKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCargaHorariaAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCargaHorariaCargaHorariaParserRuleCall_3_0 = (RuleCall)cCargaHorariaAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRequiereKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRecursosAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRecursosRecursoParserRuleCall_4_1_0 = (RuleCall)cRecursosAssignment_4_1.eContents().get(0);
		
		//Materia:
		//	"materia" name=ID "con" cargaHoraria=CargaHoraria ("requiere:" recursos+=Recurso+)?;
		public ParserRule getRule() { return rule; }

		//"materia" name=ID "con" cargaHoraria=CargaHoraria ("requiere:" recursos+=Recurso+)?
		public Group getGroup() { return cGroup; }

		//"materia"
		public Keyword getMateriaKeyword_0() { return cMateriaKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"con"
		public Keyword getConKeyword_2() { return cConKeyword_2; }

		//cargaHoraria=CargaHoraria
		public Assignment getCargaHorariaAssignment_3() { return cCargaHorariaAssignment_3; }

		//CargaHoraria
		public RuleCall getCargaHorariaCargaHorariaParserRuleCall_3_0() { return cCargaHorariaCargaHorariaParserRuleCall_3_0; }

		//("requiere:" recursos+=Recurso+)?
		public Group getGroup_4() { return cGroup_4; }

		//"requiere:"
		public Keyword getRequiereKeyword_4_0() { return cRequiereKeyword_4_0; }

		//recursos+=Recurso+
		public Assignment getRecursosAssignment_4_1() { return cRecursosAssignment_4_1; }

		//Recurso
		public RuleCall getRecursosRecursoParserRuleCall_4_1_0() { return cRecursosRecursoParserRuleCall_4_1_0; }
	}

	public class AulaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Aula");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAulaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cRecursoKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cRecursosAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cRecursosRecursoParserRuleCall_2_1_0 = (RuleCall)cRecursosAssignment_2_1.eContents().get(0);
		
		//Aula:
		//	"aula" name=ID ("recurso" recursos+=Recurso)?;
		public ParserRule getRule() { return rule; }

		//"aula" name=ID ("recurso" recursos+=Recurso)?
		public Group getGroup() { return cGroup; }

		//"aula"
		public Keyword getAulaKeyword_0() { return cAulaKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("recurso" recursos+=Recurso)?
		public Group getGroup_2() { return cGroup_2; }

		//"recurso"
		public Keyword getRecursoKeyword_2_0() { return cRecursoKeyword_2_0; }

		//recursos+=Recurso
		public Assignment getRecursosAssignment_2_1() { return cRecursosAssignment_2_1; }

		//Recurso
		public RuleCall getRecursosRecursoParserRuleCall_2_1_0() { return cRecursosRecursoParserRuleCall_2_1_0; }
	}

	public class CargaHorariaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CargaHoraria");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCargaHorariaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCantHorasAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCantHorasINTTerminalRuleCall_1_0 = (RuleCall)cCantHorasAssignment_1.eContents().get(0);
		private final Keyword cDiasKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDiasAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDiasINTTerminalRuleCall_3_0 = (RuleCall)cDiasAssignment_3.eContents().get(0);
		
		//CargaHoraria:
		//	"cargaHoraria" cantHoras=INT "dias" dias=INT;
		public ParserRule getRule() { return rule; }

		//"cargaHoraria" cantHoras=INT "dias" dias=INT
		public Group getGroup() { return cGroup; }

		//"cargaHoraria"
		public Keyword getCargaHorariaKeyword_0() { return cCargaHorariaKeyword_0; }

		//cantHoras=INT
		public Assignment getCantHorasAssignment_1() { return cCantHorasAssignment_1; }

		//INT
		public RuleCall getCantHorasINTTerminalRuleCall_1_0() { return cCantHorasINTTerminalRuleCall_1_0; }

		//"dias"
		public Keyword getDiasKeyword_2() { return cDiasKeyword_2; }

		//dias=INT
		public Assignment getDiasAssignment_3() { return cDiasAssignment_3; }

		//INT
		public RuleCall getDiasINTTerminalRuleCall_3_0() { return cDiasINTTerminalRuleCall_3_0; }
	}

	public class CargaHorariaDocenteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CargaHorariaDocente");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameProfesorParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cTieneKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTipoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTipoCargaHorariaParserRuleCall_2_0 = (RuleCall)cTipoAssignment_2.eContents().get(0);
		
		//CargaHorariaDocente:
		//	name=Profesor "tiene" tipo=CargaHoraria;
		public ParserRule getRule() { return rule; }

		//name=Profesor "tiene" tipo=CargaHoraria
		public Group getGroup() { return cGroup; }

		//name=Profesor
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//Profesor
		public RuleCall getNameProfesorParserRuleCall_0_0() { return cNameProfesorParserRuleCall_0_0; }

		//"tiene"
		public Keyword getTieneKeyword_1() { return cTieneKeyword_1; }

		//tipo=CargaHoraria
		public Assignment getTipoAssignment_2() { return cTipoAssignment_2; }

		//CargaHoraria
		public RuleCall getTipoCargaHorariaParserRuleCall_2_0() { return cTipoCargaHorariaParserRuleCall_2_0; }
	}

	public class HorarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Horario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDiaAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDiaDiaParserRuleCall_0_0 = (RuleCall)cDiaAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDesdeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDesdeHoraParserRuleCall_2_0 = (RuleCall)cDesdeAssignment_2.eContents().get(0);
		private final Keyword cAKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cHastaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cHastaHoraParserRuleCall_4_0 = (RuleCall)cHastaAssignment_4.eContents().get(0);
		private final Keyword cHsSeDictaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cMateriaAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cMateriaMateriaParserRuleCall_6_0 = (RuleCall)cMateriaAssignment_6.eContents().get(0);
		private final Keyword cEnKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cAulaAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cAulaAulaParserRuleCall_8_0 = (RuleCall)cAulaAssignment_8.eContents().get(0);
		
		//Horario:
		//	dia=Dia ":" desde=Hora "a" hasta=Hora "hs se dicta" materia=Materia "en" aula=Aula;
		public ParserRule getRule() { return rule; }

		//dia=Dia ":" desde=Hora "a" hasta=Hora "hs se dicta" materia=Materia "en" aula=Aula
		public Group getGroup() { return cGroup; }

		//dia=Dia
		public Assignment getDiaAssignment_0() { return cDiaAssignment_0; }

		//Dia
		public RuleCall getDiaDiaParserRuleCall_0_0() { return cDiaDiaParserRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//desde=Hora
		public Assignment getDesdeAssignment_2() { return cDesdeAssignment_2; }

		//Hora
		public RuleCall getDesdeHoraParserRuleCall_2_0() { return cDesdeHoraParserRuleCall_2_0; }

		//"a"
		public Keyword getAKeyword_3() { return cAKeyword_3; }

		//hasta=Hora
		public Assignment getHastaAssignment_4() { return cHastaAssignment_4; }

		//Hora
		public RuleCall getHastaHoraParserRuleCall_4_0() { return cHastaHoraParserRuleCall_4_0; }

		//"hs se dicta"
		public Keyword getHsSeDictaKeyword_5() { return cHsSeDictaKeyword_5; }

		//materia=Materia
		public Assignment getMateriaAssignment_6() { return cMateriaAssignment_6; }

		//Materia
		public RuleCall getMateriaMateriaParserRuleCall_6_0() { return cMateriaMateriaParserRuleCall_6_0; }

		//"en"
		public Keyword getEnKeyword_7() { return cEnKeyword_7; }

		//aula=Aula
		public Assignment getAulaAssignment_8() { return cAulaAssignment_8; }

		//Aula
		public RuleCall getAulaAulaParserRuleCall_8_0() { return cAulaAulaParserRuleCall_8_0; }
	}

	public class SemestreElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Semestre");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAnhoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAnhoINTTerminalRuleCall_0_0 = (RuleCall)cAnhoAssignment_0.eContents().get(0);
		private final Keyword cSemestreKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNumeroAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumeroINTTerminalRuleCall_2_0 = (RuleCall)cNumeroAssignment_2.eContents().get(0);
		
		//Semestre:
		//	anho=INT "semestre" numero=INT;
		public ParserRule getRule() { return rule; }

		//anho=INT "semestre" numero=INT
		public Group getGroup() { return cGroup; }

		//anho=INT
		public Assignment getAnhoAssignment_0() { return cAnhoAssignment_0; }

		//INT
		public RuleCall getAnhoINTTerminalRuleCall_0_0() { return cAnhoINTTerminalRuleCall_0_0; }

		//"semestre"
		public Keyword getSemestreKeyword_1() { return cSemestreKeyword_1; }

		//numero=INT
		public Assignment getNumeroAssignment_2() { return cNumeroAssignment_2; }

		//INT
		public RuleCall getNumeroINTTerminalRuleCall_2_0() { return cNumeroINTTerminalRuleCall_2_0; }
	}

	public class DiaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Dia");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLunesParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMartesParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMiercolesParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cJuevesParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cViernesParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cSabadoParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Dia:
		//	Lunes | Martes | Miercoles | Jueves | Viernes | Sabado;
		public ParserRule getRule() { return rule; }

		//Lunes | Martes | Miercoles | Jueves | Viernes | Sabado
		public Alternatives getAlternatives() { return cAlternatives; }

		//Lunes
		public RuleCall getLunesParserRuleCall_0() { return cLunesParserRuleCall_0; }

		//Martes
		public RuleCall getMartesParserRuleCall_1() { return cMartesParserRuleCall_1; }

		//Miercoles
		public RuleCall getMiercolesParserRuleCall_2() { return cMiercolesParserRuleCall_2; }

		//Jueves
		public RuleCall getJuevesParserRuleCall_3() { return cJuevesParserRuleCall_3; }

		//Viernes
		public RuleCall getViernesParserRuleCall_4() { return cViernesParserRuleCall_4; }

		//Sabado
		public RuleCall getSabadoParserRuleCall_5() { return cSabadoParserRuleCall_5; }
	}

	public class LunesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Lunes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLunesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLunesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Lunes:
		//	{Lunes} "Lunes";
		public ParserRule getRule() { return rule; }

		//{Lunes} "Lunes"
		public Group getGroup() { return cGroup; }

		//{Lunes}
		public Action getLunesAction_0() { return cLunesAction_0; }

		//"Lunes"
		public Keyword getLunesKeyword_1() { return cLunesKeyword_1; }
	}

	public class MartesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Martes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMartesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMartesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Martes:
		//	{Martes} "Martes";
		public ParserRule getRule() { return rule; }

		//{Martes} "Martes"
		public Group getGroup() { return cGroup; }

		//{Martes}
		public Action getMartesAction_0() { return cMartesAction_0; }

		//"Martes"
		public Keyword getMartesKeyword_1() { return cMartesKeyword_1; }
	}

	public class MiercolesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Miercoles");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMiercolesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMiercolesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Miercoles:
		//	{Miercoles} "Miercoles";
		public ParserRule getRule() { return rule; }

		//{Miercoles} "Miercoles"
		public Group getGroup() { return cGroup; }

		//{Miercoles}
		public Action getMiercolesAction_0() { return cMiercolesAction_0; }

		//"Miercoles"
		public Keyword getMiercolesKeyword_1() { return cMiercolesKeyword_1; }
	}

	public class JuevesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Jueves");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cJuevesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cJuevesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Jueves:
		//	{Jueves} "Jueves";
		public ParserRule getRule() { return rule; }

		//{Jueves} "Jueves"
		public Group getGroup() { return cGroup; }

		//{Jueves}
		public Action getJuevesAction_0() { return cJuevesAction_0; }

		//"Jueves"
		public Keyword getJuevesKeyword_1() { return cJuevesKeyword_1; }
	}

	public class ViernesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Viernes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cViernesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cViernesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Viernes:
		//	{Viernes} "Viernes";
		public ParserRule getRule() { return rule; }

		//{Viernes} "Viernes"
		public Group getGroup() { return cGroup; }

		//{Viernes}
		public Action getViernesAction_0() { return cViernesAction_0; }

		//"Viernes"
		public Keyword getViernesKeyword_1() { return cViernesKeyword_1; }
	}

	public class SabadoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Sabado");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSabadoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSabadoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Sabado:
		//	{Sabado} "Sabado";
		public ParserRule getRule() { return rule; }

		//{Sabado} "Sabado"
		public Group getGroup() { return cGroup; }

		//{Sabado}
		public Action getSabadoAction_0() { return cSabadoAction_0; }

		//"Sabado"
		public Keyword getSabadoKeyword_1() { return cSabadoKeyword_1; }
	}

	public class DiasElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Dias");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDiaAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDiaDiaParserRuleCall_0_0 = (RuleCall)cDiaAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cMateriaAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cMateriaMateriaParserRuleCall_1_0_0 = (RuleCall)cMateriaAssignment_1_0.eContents().get(0);
		private final Keyword cHorarioKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cHorarioAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cHorarioHorarioParserRuleCall_1_2_0 = (RuleCall)cHorarioAssignment_1_2.eContents().get(0);
		
		//Dias:
		//	dia=Dia (materia=Materia "horario" horario=Horario)?;
		public ParserRule getRule() { return rule; }

		//dia=Dia (materia=Materia "horario" horario=Horario)?
		public Group getGroup() { return cGroup; }

		//dia=Dia
		public Assignment getDiaAssignment_0() { return cDiaAssignment_0; }

		//Dia
		public RuleCall getDiaDiaParserRuleCall_0_0() { return cDiaDiaParserRuleCall_0_0; }

		//(materia=Materia "horario" horario=Horario)?
		public Group getGroup_1() { return cGroup_1; }

		//materia=Materia
		public Assignment getMateriaAssignment_1_0() { return cMateriaAssignment_1_0; }

		//Materia
		public RuleCall getMateriaMateriaParserRuleCall_1_0_0() { return cMateriaMateriaParserRuleCall_1_0_0; }

		//"horario"
		public Keyword getHorarioKeyword_1_1() { return cHorarioKeyword_1_1; }

		//horario=Horario
		public Assignment getHorarioAssignment_1_2() { return cHorarioAssignment_1_2; }

		//Horario
		public RuleCall getHorarioHorarioParserRuleCall_1_2_0() { return cHorarioHorarioParserRuleCall_1_2_0; }
	}

	public class HorariosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Horarios");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHorariosKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHorariosAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHorariosHorarioParserRuleCall_1_0 = (RuleCall)cHorariosAssignment_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Horarios:
		//	"horarios {" horarios+=Horario+ "}";
		public ParserRule getRule() { return rule; }

		//"horarios {" horarios+=Horario+ "}"
		public Group getGroup() { return cGroup; }

		//"horarios {"
		public Keyword getHorariosKeyword_0() { return cHorariosKeyword_0; }

		//horarios+=Horario+
		public Assignment getHorariosAssignment_1() { return cHorariosAssignment_1; }

		//Horario
		public RuleCall getHorariosHorarioParserRuleCall_1_0() { return cHorariosHorarioParserRuleCall_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}

	public class PlanificacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Planificacion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlanificacionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSemestreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSemestreSemestreParserRuleCall_1_0 = (RuleCall)cSemestreAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cADictarKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMateriasAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMateriasMateriaParserRuleCall_4_0 = (RuleCall)cMateriasAssignment_4.eContents().get(0);
		private final Assignment cHorariosAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cHorariosHorariosParserRuleCall_5_0 = (RuleCall)cHorariosAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Planificacion:
		//	"planificacion" semestre=Semestre "{" "a dictar:" materias+=Materia+ horarios=Horarios "}";
		public ParserRule getRule() { return rule; }

		//"planificacion" semestre=Semestre "{" "a dictar:" materias+=Materia+ horarios=Horarios "}"
		public Group getGroup() { return cGroup; }

		//"planificacion"
		public Keyword getPlanificacionKeyword_0() { return cPlanificacionKeyword_0; }

		//semestre=Semestre
		public Assignment getSemestreAssignment_1() { return cSemestreAssignment_1; }

		//Semestre
		public RuleCall getSemestreSemestreParserRuleCall_1_0() { return cSemestreSemestreParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"a dictar:"
		public Keyword getADictarKeyword_3() { return cADictarKeyword_3; }

		//materias+=Materia+
		public Assignment getMateriasAssignment_4() { return cMateriasAssignment_4; }

		//Materia
		public RuleCall getMateriasMateriaParserRuleCall_4_0() { return cMateriasMateriaParserRuleCall_4_0; }

		//horarios=Horarios
		public Assignment getHorariosAssignment_5() { return cHorariosAssignment_5; }

		//Horarios
		public RuleCall getHorariosHorariosParserRuleCall_5_0() { return cHorariosHorariosParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class RecursoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Recurso");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRecursoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		////RecursoMateria:
		////	'materia' materia=Materia '{'
		////	'requiere:' (recursos+=Recurso)+
		////	'}';
		//Recurso:
		//	"recurso" name=ID;
		public ParserRule getRule() { return rule; }

		//"recurso" name=ID //RecursoMateria:
		////	'materia' materia=Materia '{'
		////	'requiere:' (recursos+=Recurso)+
		////	'}';
		public Group getGroup() { return cGroup; }

		//"recurso"
		public Keyword getRecursoKeyword_0() { return cRecursoKeyword_0; }

		////RecursoMateria:
		////	'materia' materia=Materia '{'
		////	'requiere:' (recursos+=Recurso)+
		////	'}';
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		////RecursoMateria:
		////	'materia' materia=Materia '{'
		////	'requiere:' (recursos+=Recurso)+
		////	'}';
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	
	
	private ModelElements pModel;
	private ImportElements pImport;
	private ImportedFQNElements pImportedFQN;
	private FQNElements pFQN;
	private ProfesorElements pProfesor;
	private HoraElements pHora;
	private DedicacionElements pDedicacion;
	private SIMPLEElements pSIMPLE;
	private SEMIElements pSEMI;
	private EXCLUSIVAElements pEXCLUSIVA;
	private MateriaElements pMateria;
	private AulaElements pAula;
	private CargaHorariaElements pCargaHoraria;
	private CargaHorariaDocenteElements pCargaHorariaDocente;
	private HorarioElements pHorario;
	private SemestreElements pSemestre;
	private DiaElements pDia;
	private LunesElements pLunes;
	private MartesElements pMartes;
	private MiercolesElements pMiercoles;
	private JuevesElements pJueves;
	private ViernesElements pViernes;
	private SabadoElements pSabado;
	private DiasElements pDias;
	private HorariosElements pHorarios;
	private PlanificacionElements pPlanificacion;
	private RecursoElements pRecurso;
	
	private final Grammar grammar;

	private XbaseGrammarAccess gaXbase;

	@Inject
	public PdmGrammarAccess(GrammarProvider grammarProvider,
		XbaseGrammarAccess gaXbase) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaXbase = gaXbase;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.unq.planificador.Pdm".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public XbaseGrammarAccess getXbaseGrammarAccess() {
		return gaXbase;
	}

	
	//Model:
	//	imports+=Import* profesors+=Profesor* horas+=Hora* materias+=Materia* aulas+=Aula* cargasHorarias+=CargaHoraria*
	//	cargasHorariasDocentes+=CargaHorariaDocente* horarios+=Horarios* dias+=Dia* semestre+=Semestre*
	//	planificaciones+=Planificacion* horarios+=Horario* recursos+=Recurso*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	////recursosDeMaterias+=RecursoMateria*
	//Import:
	//	"import" importedNamespace=ImportedFQN;
	public ImportElements getImportAccess() {
		return (pImport != null) ? pImport : (pImport = new ImportElements());
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//ImportedFQN:
	//	FQN ".*"?;
	public ImportedFQNElements getImportedFQNAccess() {
		return (pImportedFQN != null) ? pImportedFQN : (pImportedFQN = new ImportedFQNElements());
	}
	
	public ParserRule getImportedFQNRule() {
		return getImportedFQNAccess().getRule();
	}

	//FQN:
	//	ID ("." ID)*;
	public FQNElements getFQNAccess() {
		return (pFQN != null) ? pFQN : (pFQN = new FQNElements());
	}
	
	public ParserRule getFQNRule() {
		return getFQNAccess().getRule();
	}

	//Profesor:
	//	"profesor" name=ID "dedicacion" dedicacion=Dedicacion;
	public ProfesorElements getProfesorAccess() {
		return (pProfesor != null) ? pProfesor : (pProfesor = new ProfesorElements());
	}
	
	public ParserRule getProfesorRule() {
		return getProfesorAccess().getRule();
	}

	//Hora:
	//	"hora" hora=INT;
	public HoraElements getHoraAccess() {
		return (pHora != null) ? pHora : (pHora = new HoraElements());
	}
	
	public ParserRule getHoraRule() {
		return getHoraAccess().getRule();
	}

	//Dedicacion:
	//	SIMPLE | SEMI | EXCLUSIVA;
	public DedicacionElements getDedicacionAccess() {
		return (pDedicacion != null) ? pDedicacion : (pDedicacion = new DedicacionElements());
	}
	
	public ParserRule getDedicacionRule() {
		return getDedicacionAccess().getRule();
	}

	//SIMPLE:
	//	{SIMPLE} "simple";
	public SIMPLEElements getSIMPLEAccess() {
		return (pSIMPLE != null) ? pSIMPLE : (pSIMPLE = new SIMPLEElements());
	}
	
	public ParserRule getSIMPLERule() {
		return getSIMPLEAccess().getRule();
	}

	//SEMI:
	//	{SEMI} "semi";
	public SEMIElements getSEMIAccess() {
		return (pSEMI != null) ? pSEMI : (pSEMI = new SEMIElements());
	}
	
	public ParserRule getSEMIRule() {
		return getSEMIAccess().getRule();
	}

	//EXCLUSIVA:
	//	{EXCLUSIVA} "exclusiva";
	public EXCLUSIVAElements getEXCLUSIVAAccess() {
		return (pEXCLUSIVA != null) ? pEXCLUSIVA : (pEXCLUSIVA = new EXCLUSIVAElements());
	}
	
	public ParserRule getEXCLUSIVARule() {
		return getEXCLUSIVAAccess().getRule();
	}

	//Materia:
	//	"materia" name=ID "con" cargaHoraria=CargaHoraria ("requiere:" recursos+=Recurso+)?;
	public MateriaElements getMateriaAccess() {
		return (pMateria != null) ? pMateria : (pMateria = new MateriaElements());
	}
	
	public ParserRule getMateriaRule() {
		return getMateriaAccess().getRule();
	}

	//Aula:
	//	"aula" name=ID ("recurso" recursos+=Recurso)?;
	public AulaElements getAulaAccess() {
		return (pAula != null) ? pAula : (pAula = new AulaElements());
	}
	
	public ParserRule getAulaRule() {
		return getAulaAccess().getRule();
	}

	//CargaHoraria:
	//	"cargaHoraria" cantHoras=INT "dias" dias=INT;
	public CargaHorariaElements getCargaHorariaAccess() {
		return (pCargaHoraria != null) ? pCargaHoraria : (pCargaHoraria = new CargaHorariaElements());
	}
	
	public ParserRule getCargaHorariaRule() {
		return getCargaHorariaAccess().getRule();
	}

	//CargaHorariaDocente:
	//	name=Profesor "tiene" tipo=CargaHoraria;
	public CargaHorariaDocenteElements getCargaHorariaDocenteAccess() {
		return (pCargaHorariaDocente != null) ? pCargaHorariaDocente : (pCargaHorariaDocente = new CargaHorariaDocenteElements());
	}
	
	public ParserRule getCargaHorariaDocenteRule() {
		return getCargaHorariaDocenteAccess().getRule();
	}

	//Horario:
	//	dia=Dia ":" desde=Hora "a" hasta=Hora "hs se dicta" materia=Materia "en" aula=Aula;
	public HorarioElements getHorarioAccess() {
		return (pHorario != null) ? pHorario : (pHorario = new HorarioElements());
	}
	
	public ParserRule getHorarioRule() {
		return getHorarioAccess().getRule();
	}

	//Semestre:
	//	anho=INT "semestre" numero=INT;
	public SemestreElements getSemestreAccess() {
		return (pSemestre != null) ? pSemestre : (pSemestre = new SemestreElements());
	}
	
	public ParserRule getSemestreRule() {
		return getSemestreAccess().getRule();
	}

	//Dia:
	//	Lunes | Martes | Miercoles | Jueves | Viernes | Sabado;
	public DiaElements getDiaAccess() {
		return (pDia != null) ? pDia : (pDia = new DiaElements());
	}
	
	public ParserRule getDiaRule() {
		return getDiaAccess().getRule();
	}

	//Lunes:
	//	{Lunes} "Lunes";
	public LunesElements getLunesAccess() {
		return (pLunes != null) ? pLunes : (pLunes = new LunesElements());
	}
	
	public ParserRule getLunesRule() {
		return getLunesAccess().getRule();
	}

	//Martes:
	//	{Martes} "Martes";
	public MartesElements getMartesAccess() {
		return (pMartes != null) ? pMartes : (pMartes = new MartesElements());
	}
	
	public ParserRule getMartesRule() {
		return getMartesAccess().getRule();
	}

	//Miercoles:
	//	{Miercoles} "Miercoles";
	public MiercolesElements getMiercolesAccess() {
		return (pMiercoles != null) ? pMiercoles : (pMiercoles = new MiercolesElements());
	}
	
	public ParserRule getMiercolesRule() {
		return getMiercolesAccess().getRule();
	}

	//Jueves:
	//	{Jueves} "Jueves";
	public JuevesElements getJuevesAccess() {
		return (pJueves != null) ? pJueves : (pJueves = new JuevesElements());
	}
	
	public ParserRule getJuevesRule() {
		return getJuevesAccess().getRule();
	}

	//Viernes:
	//	{Viernes} "Viernes";
	public ViernesElements getViernesAccess() {
		return (pViernes != null) ? pViernes : (pViernes = new ViernesElements());
	}
	
	public ParserRule getViernesRule() {
		return getViernesAccess().getRule();
	}

	//Sabado:
	//	{Sabado} "Sabado";
	public SabadoElements getSabadoAccess() {
		return (pSabado != null) ? pSabado : (pSabado = new SabadoElements());
	}
	
	public ParserRule getSabadoRule() {
		return getSabadoAccess().getRule();
	}

	//Dias:
	//	dia=Dia (materia=Materia "horario" horario=Horario)?;
	public DiasElements getDiasAccess() {
		return (pDias != null) ? pDias : (pDias = new DiasElements());
	}
	
	public ParserRule getDiasRule() {
		return getDiasAccess().getRule();
	}

	//Horarios:
	//	"horarios {" horarios+=Horario+ "}";
	public HorariosElements getHorariosAccess() {
		return (pHorarios != null) ? pHorarios : (pHorarios = new HorariosElements());
	}
	
	public ParserRule getHorariosRule() {
		return getHorariosAccess().getRule();
	}

	//Planificacion:
	//	"planificacion" semestre=Semestre "{" "a dictar:" materias+=Materia+ horarios=Horarios "}";
	public PlanificacionElements getPlanificacionAccess() {
		return (pPlanificacion != null) ? pPlanificacion : (pPlanificacion = new PlanificacionElements());
	}
	
	public ParserRule getPlanificacionRule() {
		return getPlanificacionAccess().getRule();
	}

	////RecursoMateria:
	////	'materia' materia=Materia '{'
	////	'requiere:' (recursos+=Recurso)+
	////	'}';
	//Recurso:
	//	"recurso" name=ID;
	public RecursoElements getRecursoAccess() {
		return (pRecurso != null) ? pRecurso : (pRecurso = new RecursoElements());
	}
	
	public ParserRule getRecursoRule() {
		return getRecursoAccess().getRule();
	}

	//XExpression:
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaXbase.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}

	//XAssignment returns XExpression:
	//	{XAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign value=XAssignment | XOrExpression
	//	(=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMultiAssign])
	//	rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaXbase.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}

	//OpSingleAssign:
	//	"=";
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaXbase.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}

	//OpMultiAssign:
	//	"+=" | "-=" | "*=" | "/=" | "%=" | "<" "<" "=" | ">" ">"? ">=";
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaXbase.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}

	//XOrExpression returns XExpression:
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaXbase.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}

	//OpOr:
	//	"||";
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaXbase.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}

	//XAndExpression returns XExpression:
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaXbase.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}

	//OpAnd:
	//	"&&";
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaXbase.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}

	//XEqualityExpression returns XExpression:
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaXbase.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//	"==" | "!=" | "===" | "!==";
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaXbase.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//XRelationalExpression returns XExpression:
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} "instanceof") type=JvmTypeReference | =>
	//	({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaXbase.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}

	//OpCompare:
	//	">=" | "<" "=" | ">" | "<";
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaXbase.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}

	//XOtherOperatorExpression returns XExpression:
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaXbase.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}

	//OpOther:
	//	"->" | "..<" | ">" ".." | ".." | "=>" | ">" (=> (">" ">") | ">") | "<" (=> ("<" "<") | "<" | "=>") | "<>" | "?:";
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaXbase.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}

	//XAdditiveExpression returns XExpression:
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaXbase.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//	"+" | "-";
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaXbase.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//XMultiplicativeExpression returns XExpression:
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaXbase.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//	"*" | "**" | "/" | "%";
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaXbase.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//XUnaryOperation returns XExpression:
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XUnaryOperation | XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaXbase.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}

	//OpUnary:
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaXbase.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}

	//XCastedExpression returns XExpression:
	//	XPostfixOperation (=> ({XCastedExpression.target=current} "as") type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaXbase.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}

	//XPostfixOperation returns XExpression:
	//	XMemberFeatureCall => ({XPostfixOperation.operand=current} feature=[types::JvmIdentifiableElement|OpPostfix])?;
	public XbaseGrammarAccess.XPostfixOperationElements getXPostfixOperationAccess() {
		return gaXbase.getXPostfixOperationAccess();
	}
	
	public ParserRule getXPostfixOperationRule() {
		return getXPostfixOperationAccess().getRule();
	}

	//OpPostfix:
	//	"++" | "--";
	public XbaseGrammarAccess.OpPostfixElements getOpPostfixAccess() {
		return gaXbase.getOpPostfixAccess();
	}
	
	public ParserRule getOpPostfixRule() {
		return getOpPostfixAccess().getRule();
	}

	//XMemberFeatureCall returns XExpression:
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} ("." | explicitStatic?="::")
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign) value=XAssignment | =>
	//	({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." | explicitStatic?="::")) ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?="(" (memberCallArguments+=XShortClosure |
	//	memberCallArguments+=XExpression ("," memberCallArguments+=XExpression)*)? ")")? memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaXbase.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}

	//XPrimaryExpression returns XExpression:
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XSynchronizedExpression | XFeatureCall | XLiteral |
	//	XIfExpression | XForLoopExpression | XBasicForLoopExpression | XWhileExpression | XDoWhileExpression |
	//	XThrowExpression | XReturnExpression | XTryCatchFinallyExpression | XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaXbase.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}

	//XLiteral returns XExpression:
	//	XCollectionLiteral | XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaXbase.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}

	//XCollectionLiteral:
	//	XSetLiteral | XListLiteral;
	public XbaseGrammarAccess.XCollectionLiteralElements getXCollectionLiteralAccess() {
		return gaXbase.getXCollectionLiteralAccess();
	}
	
	public ParserRule getXCollectionLiteralRule() {
		return getXCollectionLiteralAccess().getRule();
	}

	//XSetLiteral:
	//	{XSetLiteral} "#" "{" (elements+=XExpression ("," elements+=XExpression)*)? "}";
	public XbaseGrammarAccess.XSetLiteralElements getXSetLiteralAccess() {
		return gaXbase.getXSetLiteralAccess();
	}
	
	public ParserRule getXSetLiteralRule() {
		return getXSetLiteralAccess().getRule();
	}

	//XListLiteral:
	//	{XListLiteral} "#" "[" (elements+=XExpression ("," elements+=XExpression)*)? "]";
	public XbaseGrammarAccess.XListLiteralElements getXListLiteralAccess() {
		return gaXbase.getXListLiteralAccess();
	}
	
	public ParserRule getXListLiteralRule() {
		return getXListLiteralAccess().getRule();
	}

	//XClosure returns XExpression:
	//	=> ({XClosure} "[") => ((declaredFormalParameters+=JvmFormalParameter (","
	//	declaredFormalParameters+=JvmFormalParameter)*)? explicitSyntax?="|")? expression=XExpressionInClosure "]";
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaXbase.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}

	//XExpressionInClosure returns XExpression:
	//	{XBlockExpression} (expressions+=XExpressionOrVarDeclaration ";"?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaXbase.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}

	//XShortClosure returns XExpression:
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter ("," declaredFormalParameters+=JvmFormalParameter)*)?
	//	explicitSyntax?="|") expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaXbase.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}

	//XParenthesizedExpression returns XExpression:
	//	"(" XExpression ")";
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaXbase.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}

	//XIfExpression returns XExpression:
	//	{XIfExpression} "if" "(" if=XExpression ")" then=XExpression ("else" else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaXbase.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}

	//XSwitchExpression returns XExpression:
	//	{XSwitchExpression} "switch" (=> ("(" declaredParam=JvmFormalParameter ":") switch=XExpression ")" | =>
	//	(declaredParam=JvmFormalParameter ":")? switch=XExpression) "{" cases+=XCasePart* ("default" ":" default=XExpression)?
	//	"}";
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaXbase.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}

	//XCasePart:
	//	{XCasePart} typeGuard=JvmTypeReference? ("case" case=XExpression)? (":" then=XExpression | ",");
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaXbase.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}

	//XForLoopExpression returns XExpression:
	//	=> ({XForLoopExpression} "for" "(" declaredParam=JvmFormalParameter ":") forExpression=XExpression ")"
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaXbase.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}

	//XBasicForLoopExpression returns XExpression:
	//	{XBasicForLoopExpression} "for" "(" (initExpressions+=XExpressionOrVarDeclaration (","
	//	initExpressions+=XExpressionOrVarDeclaration)*)? ";" expression=XExpression? ";" (updateExpressions+=XExpression (","
	//	updateExpressions+=XExpression)*)? ")" eachExpression=XExpression;
	public XbaseGrammarAccess.XBasicForLoopExpressionElements getXBasicForLoopExpressionAccess() {
		return gaXbase.getXBasicForLoopExpressionAccess();
	}
	
	public ParserRule getXBasicForLoopExpressionRule() {
		return getXBasicForLoopExpressionAccess().getRule();
	}

	//XWhileExpression returns XExpression:
	//	{XWhileExpression} "while" "(" predicate=XExpression ")" body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaXbase.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}

	//XDoWhileExpression returns XExpression:
	//	{XDoWhileExpression} "do" body=XExpression "while" "(" predicate=XExpression ")";
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaXbase.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}

	//XBlockExpression returns XExpression:
	//	{XBlockExpression} "{" (expressions+=XExpressionOrVarDeclaration ";"?)* "}";
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaXbase.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}

	//XExpressionOrVarDeclaration returns XExpression:
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionOrVarDeclarationElements getXExpressionOrVarDeclarationAccess() {
		return gaXbase.getXExpressionOrVarDeclarationAccess();
	}
	
	public ParserRule getXExpressionOrVarDeclarationRule() {
		return getXExpressionOrVarDeclarationAccess().getRule();
	}

	//XVariableDeclaration returns XExpression:
	//	{XVariableDeclaration} (writeable?="var" | "val") (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ("="
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaXbase.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaXbase.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//FullJvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaXbase.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}

	//XFeatureCall returns XExpression:
	//	{XFeatureCall} ("<" typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?="(" (featureCallArguments+=XShortClosure
	//	| featureCallArguments+=XExpression ("," featureCallArguments+=XExpression)*)? ")")? featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaXbase.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}

	//FeatureCallID:
	//	ValidID | "extends" | "static" | "import" | "extension";
	public XbaseGrammarAccess.FeatureCallIDElements getFeatureCallIDAccess() {
		return gaXbase.getFeatureCallIDAccess();
	}
	
	public ParserRule getFeatureCallIDRule() {
		return getFeatureCallIDAccess().getRule();
	}

	//IdOrSuper:
	//	FeatureCallID | "super";
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaXbase.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}

	//XConstructorCall returns XExpression:
	//	{XConstructorCall} "new" constructor=[types::JvmConstructor|QualifiedName] ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")? (=>
	//	explicitConstructorCall?="(" (arguments+=XShortClosure | arguments+=XExpression ("," arguments+=XExpression)*)? ")")?
	//	arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaXbase.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}

	//XBooleanLiteral returns XExpression:
	//	{XBooleanLiteral} ("false" | isTrue?="true");
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaXbase.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}

	//XNullLiteral returns XExpression:
	//	{XNullLiteral} "null";
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaXbase.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}

	//XNumberLiteral returns XExpression:
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaXbase.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}

	//XStringLiteral returns XExpression:
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaXbase.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}

	//XTypeLiteral returns XExpression:
	//	{XTypeLiteral} "typeof" "(" type=[types::JvmType|QualifiedName] arrayDimensions+=ArrayBrackets* ")";
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaXbase.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}

	//XThrowExpression returns XExpression:
	//	{XThrowExpression} "throw" expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaXbase.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}

	//XReturnExpression returns XExpression:
	//	{XReturnExpression} "return" -> expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaXbase.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}

	//XTryCatchFinallyExpression returns XExpression:
	//	{XTryCatchFinallyExpression} "try" expression=XExpression (catchClauses+=XCatchClause+ ("finally"
	//	finallyExpression=XExpression)? | "finally" finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaXbase.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}

	//XSynchronizedExpression returns XExpression:
	//	=> ({XSynchronizedExpression} "synchronized" "(") param=XExpression ")" expression=XExpression;
	public XbaseGrammarAccess.XSynchronizedExpressionElements getXSynchronizedExpressionAccess() {
		return gaXbase.getXSynchronizedExpressionAccess();
	}
	
	public ParserRule getXSynchronizedExpressionRule() {
		return getXSynchronizedExpressionAccess().getRule();
	}

	//XCatchClause:
	//	"catch" "(" declaredParam=FullJvmFormalParameter ")" expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaXbase.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}

	//QualifiedName:
	//	ValidID ("." ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Number hidden():
	//	HEX | (INT | DECIMAL) ("." (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaXbase.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	/// **
	// * Dummy rule, for "better" downwards compatibility, since GrammarAccess generates non-static inner classes, 
	// * which makes downstream grammars break on classloading, when a rule is removed.
	// * / StaticQualifier:
	//	(ValidID "::")+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaXbase.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}

	//terminal HEX:
	//	("0x" | "0X") ("0".."9" | "a".."f" | "A".."F" | "_")+ ("#" (("b" | "B") ("i" | "I") | ("l" | "L")))?;
	public TerminalRule getHEXRule() {
		return gaXbase.getHEXRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9" ("0".."9" | "_")*;
	public TerminalRule getINTRule() {
		return gaXbase.getINTRule();
	} 

	//terminal DECIMAL:
	//	INT (("e" | "E") ("+" | "-")? INT)? (("b" | "B") ("i" | "I" | "d" | "D") | ("l" | "L" | "d" | "D" | "f" | "F"))?;
	public TerminalRule getDECIMALRule() {
		return gaXbase.getDECIMALRule();
	} 

	//JvmTypeReference:
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} ArrayBrackets)* |
	//	XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaXbase.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//ArrayBrackets:
	//	"[" "]";
	public XtypeGrammarAccess.ArrayBracketsElements getArrayBracketsAccess() {
		return gaXbase.getArrayBracketsAccess();
	}
	
	public ParserRule getArrayBracketsRule() {
		return getArrayBracketsAccess().getRule();
	}

	//XFunctionTypeRef:
	//	("(" (paramTypes+=JvmTypeReference ("," paramTypes+=JvmTypeReference)*)? ")")? "=>" returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaXbase.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}

	//JvmParameterizedTypeReference:
	//	type=[JvmType|QualifiedName] ("<" arguments+=JvmArgumentTypeReference ("," arguments+=JvmArgumentTypeReference)*
	//	">")?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaXbase.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}

	//JvmArgumentTypeReference returns JvmTypeReference:
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaXbase.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}

	//JvmWildcardTypeReference:
	//	{JvmWildcardTypeReference} "?" (constraints+=JvmUpperBound | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaXbase.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}

	//JvmUpperBound:
	//	"extends" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaXbase.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}

	//JvmUpperBoundAnded returns JvmUpperBound:
	//	"&" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaXbase.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}

	//JvmLowerBound:
	//	"super" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaXbase.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}

	//JvmTypeParameter:
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded*)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaXbase.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}

	//QualifiedNameWithWildcard:
	//	QualifiedName "." "*";
	public XtypeGrammarAccess.QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return gaXbase.getQualifiedNameWithWildcardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//ValidID:
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaXbase.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//XImportSection:
	//	importDeclarations+=XImportDeclaration+;
	public XtypeGrammarAccess.XImportSectionElements getXImportSectionAccess() {
		return gaXbase.getXImportSectionAccess();
	}
	
	public ParserRule getXImportSectionRule() {
		return getXImportSectionAccess().getRule();
	}

	//XImportDeclaration:
	//	"import" (static?="static" extension?="extension"? importedType=[JvmDeclaredType|QualifiedNameInStaticImport]
	//	(wildcard?="*" | memberName=ValidID) | importedType=[JvmDeclaredType|QualifiedName] |
	//	importedNamespace=QualifiedNameWithWildcard) ";"?;
	public XtypeGrammarAccess.XImportDeclarationElements getXImportDeclarationAccess() {
		return gaXbase.getXImportDeclarationAccess();
	}
	
	public ParserRule getXImportDeclarationRule() {
		return getXImportDeclarationAccess().getRule();
	}

	//QualifiedNameInStaticImport:
	//	(ValidID ".")+;
	public XtypeGrammarAccess.QualifiedNameInStaticImportElements getQualifiedNameInStaticImportAccess() {
		return gaXbase.getQualifiedNameInStaticImportAccess();
	}
	
	public ParserRule getQualifiedNameInStaticImportRule() {
		return getQualifiedNameInStaticImportAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "$" | "_") ("a".."z" | "A".."Z" | "$" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaXbase.getIDRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaXbase.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaXbase.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaXbase.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaXbase.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaXbase.getANY_OTHERRule();
	} 
}
