/*
* generated by Xtext
*/
package org.xtext.unq.planificador.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class PdmGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cElementosPrimariosAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cElementosPrimariosElementosPrimariosParserRuleCall_0_0 = (RuleCall)cElementosPrimariosAssignment_0.eContents().get(0);
		private final Assignment cElementosSecundariosAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementosSecundariosElementosSecundariosParserRuleCall_1_0 = (RuleCall)cElementosSecundariosAssignment_1.eContents().get(0);
		private final Assignment cPlanificacionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPlanificacionPlanificacionParserRuleCall_2_0 = (RuleCall)cPlanificacionAssignment_2.eContents().get(0);
		
		//Model:
		//	elementosPrimarios+=ElementosPrimarios elementosSecundarios+=ElementosSecundarios planificacion+=Planificacion;
		public ParserRule getRule() { return rule; }

		//elementosPrimarios+=ElementosPrimarios elementosSecundarios+=ElementosSecundarios planificacion+=Planificacion
		public Group getGroup() { return cGroup; }

		//elementosPrimarios+=ElementosPrimarios
		public Assignment getElementosPrimariosAssignment_0() { return cElementosPrimariosAssignment_0; }

		//ElementosPrimarios
		public RuleCall getElementosPrimariosElementosPrimariosParserRuleCall_0_0() { return cElementosPrimariosElementosPrimariosParserRuleCall_0_0; }

		//elementosSecundarios+=ElementosSecundarios
		public Assignment getElementosSecundariosAssignment_1() { return cElementosSecundariosAssignment_1; }

		//ElementosSecundarios
		public RuleCall getElementosSecundariosElementosSecundariosParserRuleCall_1_0() { return cElementosSecundariosElementosSecundariosParserRuleCall_1_0; }

		//planificacion+=Planificacion
		public Assignment getPlanificacionAssignment_2() { return cPlanificacionAssignment_2; }

		//Planificacion
		public RuleCall getPlanificacionPlanificacionParserRuleCall_2_0() { return cPlanificacionPlanificacionParserRuleCall_2_0; }
	}

	public class ElementosPrimariosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ElementosPrimarios");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cProfesorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAsignacionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMateriaParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ElementosPrimarios:
		//	Profesor | Asignacion | Materia;
		public ParserRule getRule() { return rule; }

		//Profesor | Asignacion | Materia
		public Alternatives getAlternatives() { return cAlternatives; }

		//Profesor
		public RuleCall getProfesorParserRuleCall_0() { return cProfesorParserRuleCall_0; }

		//Asignacion
		public RuleCall getAsignacionParserRuleCall_1() { return cAsignacionParserRuleCall_1; }

		//Materia
		public RuleCall getMateriaParserRuleCall_2() { return cMateriaParserRuleCall_2; }
	}

	public class ElementosSecundariosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ElementosSecundarios");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAulaParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRecursoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ElementosSecundarios:
		//	Aula | Recurso;
		public ParserRule getRule() { return rule; }

		//Aula | Recurso
		public Alternatives getAlternatives() { return cAlternatives; }

		//Aula
		public RuleCall getAulaParserRuleCall_0() { return cAulaParserRuleCall_0; }

		//Recurso
		public RuleCall getRecursoParserRuleCall_1() { return cRecursoParserRuleCall_1; }
	}

	public class ProfesorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Profesor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProfesorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cDedicacionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDedicacionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDedicacionDedicacionParserRuleCall_3_0 = (RuleCall)cDedicacionAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDisponibilidadKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDisponibilidadAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDisponibilidadDisponibilidadParserRuleCall_4_1_0 = (RuleCall)cDisponibilidadAssignment_4_1.eContents().get(0);
		
		//Profesor:
		//	"profesor" name=ID "dedicacion" dedicacion=Dedicacion ("disponibilidad" disponibilidad=Disponibilidad)?;
		public ParserRule getRule() { return rule; }

		//"profesor" name=ID "dedicacion" dedicacion=Dedicacion ("disponibilidad" disponibilidad=Disponibilidad)?
		public Group getGroup() { return cGroup; }

		//"profesor"
		public Keyword getProfesorKeyword_0() { return cProfesorKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"dedicacion"
		public Keyword getDedicacionKeyword_2() { return cDedicacionKeyword_2; }

		//dedicacion=Dedicacion
		public Assignment getDedicacionAssignment_3() { return cDedicacionAssignment_3; }

		//Dedicacion
		public RuleCall getDedicacionDedicacionParserRuleCall_3_0() { return cDedicacionDedicacionParserRuleCall_3_0; }

		//("disponibilidad" disponibilidad=Disponibilidad)?
		public Group getGroup_4() { return cGroup_4; }

		//"disponibilidad"
		public Keyword getDisponibilidadKeyword_4_0() { return cDisponibilidadKeyword_4_0; }

		//disponibilidad=Disponibilidad
		public Assignment getDisponibilidadAssignment_4_1() { return cDisponibilidadAssignment_4_1; }

		//Disponibilidad
		public RuleCall getDisponibilidadDisponibilidadParserRuleCall_4_1_0() { return cDisponibilidadDisponibilidadParserRuleCall_4_1_0; }
	}

	public class DisponibilidadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Disponibilidad");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cNoPuedeKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cDiasAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cDiasDiaParserRuleCall_0_1_0 = (RuleCall)cDiasAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cPuedeKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDiasAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDiasDiaParserRuleCall_1_1_0 = (RuleCall)cDiasAssignment_1_1.eContents().get(0);
		private final Keyword cDeKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cInicioAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cInicioINTTerminalRuleCall_1_3_0 = (RuleCall)cInicioAssignment_1_3.eContents().get(0);
		private final Keyword cAKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		private final Assignment cFinAssignment_1_5 = (Assignment)cGroup_1.eContents().get(5);
		private final RuleCall cFinINTTerminalRuleCall_1_5_0 = (RuleCall)cFinAssignment_1_5.eContents().get(0);
		
		//Disponibilidad:
		//	("no puede" dias+=Dia*)? ("puede" dias+=Dia* "de" inicio=INT "a" fin=INT);
		public ParserRule getRule() { return rule; }

		//("no puede" dias+=Dia*)? ("puede" dias+=Dia* "de" inicio=INT "a" fin=INT)
		public Group getGroup() { return cGroup; }

		//("no puede" dias+=Dia*)?
		public Group getGroup_0() { return cGroup_0; }

		//"no puede"
		public Keyword getNoPuedeKeyword_0_0() { return cNoPuedeKeyword_0_0; }

		//dias+=Dia*
		public Assignment getDiasAssignment_0_1() { return cDiasAssignment_0_1; }

		//Dia
		public RuleCall getDiasDiaParserRuleCall_0_1_0() { return cDiasDiaParserRuleCall_0_1_0; }

		//"puede" dias+=Dia* "de" inicio=INT "a" fin=INT
		public Group getGroup_1() { return cGroup_1; }

		//"puede"
		public Keyword getPuedeKeyword_1_0() { return cPuedeKeyword_1_0; }

		//dias+=Dia*
		public Assignment getDiasAssignment_1_1() { return cDiasAssignment_1_1; }

		//Dia
		public RuleCall getDiasDiaParserRuleCall_1_1_0() { return cDiasDiaParserRuleCall_1_1_0; }

		//"de"
		public Keyword getDeKeyword_1_2() { return cDeKeyword_1_2; }

		//inicio=INT
		public Assignment getInicioAssignment_1_3() { return cInicioAssignment_1_3; }

		//INT
		public RuleCall getInicioINTTerminalRuleCall_1_3_0() { return cInicioINTTerminalRuleCall_1_3_0; }

		//"a"
		public Keyword getAKeyword_1_4() { return cAKeyword_1_4; }

		//fin=INT
		public Assignment getFinAssignment_1_5() { return cFinAssignment_1_5; }

		//INT
		public RuleCall getFinINTTerminalRuleCall_1_5_0() { return cFinINTTerminalRuleCall_1_5_0; }
	}

	public class DedicacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Dedicacion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cSIMPLEAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cSimpleKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cSEMIAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cSemiKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cEXCLUSIVAAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cExclusivaKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		
		//Dedicacion:
		//	{SIMPLE} "Simple" | {SEMI} "Semi" | {EXCLUSIVA} "Exclusiva";
		public ParserRule getRule() { return rule; }

		//{SIMPLE} "Simple" | {SEMI} "Semi" | {EXCLUSIVA} "Exclusiva"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{SIMPLE} "Simple"
		public Group getGroup_0() { return cGroup_0; }

		//{SIMPLE}
		public Action getSIMPLEAction_0_0() { return cSIMPLEAction_0_0; }

		//"Simple"
		public Keyword getSimpleKeyword_0_1() { return cSimpleKeyword_0_1; }

		//{SEMI} "Semi"
		public Group getGroup_1() { return cGroup_1; }

		//{SEMI}
		public Action getSEMIAction_1_0() { return cSEMIAction_1_0; }

		//"Semi"
		public Keyword getSemiKeyword_1_1() { return cSemiKeyword_1_1; }

		//{EXCLUSIVA} "Exclusiva"
		public Group getGroup_2() { return cGroup_2; }

		//{EXCLUSIVA}
		public Action getEXCLUSIVAAction_2_0() { return cEXCLUSIVAAction_2_0; }

		//"Exclusiva"
		public Keyword getExclusivaKeyword_2_1() { return cExclusivaKeyword_2_1; }
	}

	public class MateriaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Materia");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMateriaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cConKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCargaHorariaAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCargaHorariaCargaHorariaParserRuleCall_3_0 = (RuleCall)cCargaHorariaAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRequiereKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRecursosAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRecursosRecursoParserRuleCall_4_1_0 = (RuleCall)cRecursosAssignment_4_1.eContents().get(0);
		
		//Materia:
		//	"materia" name=ID "con" cargaHoraria=CargaHoraria ("requiere:" recursos+=Recurso+)?;
		public ParserRule getRule() { return rule; }

		//"materia" name=ID "con" cargaHoraria=CargaHoraria ("requiere:" recursos+=Recurso+)?
		public Group getGroup() { return cGroup; }

		//"materia"
		public Keyword getMateriaKeyword_0() { return cMateriaKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"con"
		public Keyword getConKeyword_2() { return cConKeyword_2; }

		//cargaHoraria=CargaHoraria
		public Assignment getCargaHorariaAssignment_3() { return cCargaHorariaAssignment_3; }

		//CargaHoraria
		public RuleCall getCargaHorariaCargaHorariaParserRuleCall_3_0() { return cCargaHorariaCargaHorariaParserRuleCall_3_0; }

		//("requiere:" recursos+=Recurso+)?
		public Group getGroup_4() { return cGroup_4; }

		//"requiere:"
		public Keyword getRequiereKeyword_4_0() { return cRequiereKeyword_4_0; }

		//recursos+=Recurso+
		public Assignment getRecursosAssignment_4_1() { return cRecursosAssignment_4_1; }

		//Recurso
		public RuleCall getRecursosRecursoParserRuleCall_4_1_0() { return cRecursosRecursoParserRuleCall_4_1_0; }
	}

	public class AulaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Aula");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAulaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cRecursoKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cRecursosAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cRecursosRecursoParserRuleCall_2_1_0 = (RuleCall)cRecursosAssignment_2_1.eContents().get(0);
		private final Keyword cCapacidadKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCapacidadAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCapacidadINTTerminalRuleCall_4_0 = (RuleCall)cCapacidadAssignment_4.eContents().get(0);
		
		//Aula:
		//	"aula" name=ID ("recurso" recursos+=Recurso)? "capacidad" capacidad=INT;
		public ParserRule getRule() { return rule; }

		//"aula" name=ID ("recurso" recursos+=Recurso)? "capacidad" capacidad=INT
		public Group getGroup() { return cGroup; }

		//"aula"
		public Keyword getAulaKeyword_0() { return cAulaKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("recurso" recursos+=Recurso)?
		public Group getGroup_2() { return cGroup_2; }

		//"recurso"
		public Keyword getRecursoKeyword_2_0() { return cRecursoKeyword_2_0; }

		//recursos+=Recurso
		public Assignment getRecursosAssignment_2_1() { return cRecursosAssignment_2_1; }

		//Recurso
		public RuleCall getRecursosRecursoParserRuleCall_2_1_0() { return cRecursosRecursoParserRuleCall_2_1_0; }

		//"capacidad"
		public Keyword getCapacidadKeyword_3() { return cCapacidadKeyword_3; }

		//capacidad=INT
		public Assignment getCapacidadAssignment_4() { return cCapacidadAssignment_4; }

		//INT
		public RuleCall getCapacidadINTTerminalRuleCall_4_0() { return cCapacidadINTTerminalRuleCall_4_0; }
	}

	public class CargaHorariaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CargaHoraria");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHorasSemanalesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCantHorasAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCantHorasINTTerminalRuleCall_1_0 = (RuleCall)cCantHorasAssignment_1.eContents().get(0);
		private final Keyword cCantidadDeDiasKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDiasSemanalesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDiasSemanalesINTTerminalRuleCall_3_0 = (RuleCall)cDiasSemanalesAssignment_3.eContents().get(0);
		
		//CargaHoraria:
		//	"horasSemanales" cantHoras=INT "cantidadDeDias" diasSemanales=INT;
		public ParserRule getRule() { return rule; }

		//"horasSemanales" cantHoras=INT "cantidadDeDias" diasSemanales=INT
		public Group getGroup() { return cGroup; }

		//"horasSemanales"
		public Keyword getHorasSemanalesKeyword_0() { return cHorasSemanalesKeyword_0; }

		//cantHoras=INT
		public Assignment getCantHorasAssignment_1() { return cCantHorasAssignment_1; }

		//INT
		public RuleCall getCantHorasINTTerminalRuleCall_1_0() { return cCantHorasINTTerminalRuleCall_1_0; }

		//"cantidadDeDias"
		public Keyword getCantidadDeDiasKeyword_2() { return cCantidadDeDiasKeyword_2; }

		//diasSemanales=INT
		public Assignment getDiasSemanalesAssignment_3() { return cDiasSemanalesAssignment_3; }

		//INT
		public RuleCall getDiasSemanalesINTTerminalRuleCall_3_0() { return cDiasSemanalesINTTerminalRuleCall_3_0; }
	}

	public class HorarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Horario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDesdeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDesdeINTTerminalRuleCall_0_0 = (RuleCall)cDesdeAssignment_0.eContents().get(0);
		private final Keyword cAKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cHastaAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cHastaINTTerminalRuleCall_2_0 = (RuleCall)cHastaAssignment_2.eContents().get(0);
		
		//Horario:
		//	desde=INT "a" hasta=INT;
		public ParserRule getRule() { return rule; }

		//desde=INT "a" hasta=INT
		public Group getGroup() { return cGroup; }

		//desde=INT
		public Assignment getDesdeAssignment_0() { return cDesdeAssignment_0; }

		//INT
		public RuleCall getDesdeINTTerminalRuleCall_0_0() { return cDesdeINTTerminalRuleCall_0_0; }

		//"a"
		public Keyword getAKeyword_1() { return cAKeyword_1; }

		//hasta=INT
		public Assignment getHastaAssignment_2() { return cHastaAssignment_2; }

		//INT
		public RuleCall getHastaINTTerminalRuleCall_2_0() { return cHastaINTTerminalRuleCall_2_0; }
	}

	public class SemestreElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Semestre");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAnhoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAnhoINTTerminalRuleCall_0_0 = (RuleCall)cAnhoAssignment_0.eContents().get(0);
		private final Keyword cSemestreKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNumeroAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumeroINTTerminalRuleCall_2_0 = (RuleCall)cNumeroAssignment_2.eContents().get(0);
		
		//Semestre:
		//	anho=INT "semestre" numero=INT;
		public ParserRule getRule() { return rule; }

		//anho=INT "semestre" numero=INT
		public Group getGroup() { return cGroup; }

		//anho=INT
		public Assignment getAnhoAssignment_0() { return cAnhoAssignment_0; }

		//INT
		public RuleCall getAnhoINTTerminalRuleCall_0_0() { return cAnhoINTTerminalRuleCall_0_0; }

		//"semestre"
		public Keyword getSemestreKeyword_1() { return cSemestreKeyword_1; }

		//numero=INT
		public Assignment getNumeroAssignment_2() { return cNumeroAssignment_2; }

		//INT
		public RuleCall getNumeroINTTerminalRuleCall_2_0() { return cNumeroINTTerminalRuleCall_2_0; }
	}

	public class DiaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Dia");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cLunesAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cLunesKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cMartesAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cMartesKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cMiercolesAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cMiercolesKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cJuevesAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cJuevesKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cViernesAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Keyword cViernesKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cSabadoAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Keyword cSabadoKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		
		//Dia:
		//	{Lunes} "Lunes" | {Martes} "Martes" | {Miercoles} "Miercoles" | {Jueves} "Jueves" | {Viernes} "Viernes" | {Sabado}
		//	"Sabado";
		public ParserRule getRule() { return rule; }

		//{Lunes} "Lunes" | {Martes} "Martes" | {Miercoles} "Miercoles" | {Jueves} "Jueves" | {Viernes} "Viernes" | {Sabado}
		//"Sabado"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{Lunes} "Lunes"
		public Group getGroup_0() { return cGroup_0; }

		//{Lunes}
		public Action getLunesAction_0_0() { return cLunesAction_0_0; }

		//"Lunes"
		public Keyword getLunesKeyword_0_1() { return cLunesKeyword_0_1; }

		//{Martes} "Martes"
		public Group getGroup_1() { return cGroup_1; }

		//{Martes}
		public Action getMartesAction_1_0() { return cMartesAction_1_0; }

		//"Martes"
		public Keyword getMartesKeyword_1_1() { return cMartesKeyword_1_1; }

		//{Miercoles} "Miercoles"
		public Group getGroup_2() { return cGroup_2; }

		//{Miercoles}
		public Action getMiercolesAction_2_0() { return cMiercolesAction_2_0; }

		//"Miercoles"
		public Keyword getMiercolesKeyword_2_1() { return cMiercolesKeyword_2_1; }

		//{Jueves} "Jueves"
		public Group getGroup_3() { return cGroup_3; }

		//{Jueves}
		public Action getJuevesAction_3_0() { return cJuevesAction_3_0; }

		//"Jueves"
		public Keyword getJuevesKeyword_3_1() { return cJuevesKeyword_3_1; }

		//{Viernes} "Viernes"
		public Group getGroup_4() { return cGroup_4; }

		//{Viernes}
		public Action getViernesAction_4_0() { return cViernesAction_4_0; }

		//"Viernes"
		public Keyword getViernesKeyword_4_1() { return cViernesKeyword_4_1; }

		//{Sabado} "Sabado"
		public Group getGroup_5() { return cGroup_5; }

		//{Sabado}
		public Action getSabadoAction_5_0() { return cSabadoAction_5_0; }

		//"Sabado"
		public Keyword getSabadoKeyword_5_1() { return cSabadoKeyword_5_1; }
	}

	public class AsignacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Asignacion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMateriaAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cMateriaMateriaCrossReference_0_0 = (CrossReference)cMateriaAssignment_0.eContents().get(0);
		private final RuleCall cMateriaMateriaIDTerminalRuleCall_0_0_1 = (RuleCall)cMateriaMateriaCrossReference_0_0.eContents().get(1);
		private final Keyword cLaDictaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cProfesoresAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cProfesoresProfesorCrossReference_2_0 = (CrossReference)cProfesoresAssignment_2.eContents().get(0);
		private final RuleCall cProfesoresProfesorIDTerminalRuleCall_2_0_1 = (RuleCall)cProfesoresProfesorCrossReference_2_0.eContents().get(1);
		private final Keyword cSeDictaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAulaHorariosAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAulaHorariosAulaHorarioParserRuleCall_4_0 = (RuleCall)cAulaHorariosAssignment_4.eContents().get(0);
		
		//Asignacion:
		//	materia=[Materia] "la dicta" profesores+=[Profesor]+ "se dicta:" aulaHorarios+=AulaHorario+;
		public ParserRule getRule() { return rule; }

		//materia=[Materia] "la dicta" profesores+=[Profesor]+ "se dicta:" aulaHorarios+=AulaHorario+
		public Group getGroup() { return cGroup; }

		//materia=[Materia]
		public Assignment getMateriaAssignment_0() { return cMateriaAssignment_0; }

		//[Materia]
		public CrossReference getMateriaMateriaCrossReference_0_0() { return cMateriaMateriaCrossReference_0_0; }

		//ID
		public RuleCall getMateriaMateriaIDTerminalRuleCall_0_0_1() { return cMateriaMateriaIDTerminalRuleCall_0_0_1; }

		//"la dicta"
		public Keyword getLaDictaKeyword_1() { return cLaDictaKeyword_1; }

		//profesores+=[Profesor]+
		public Assignment getProfesoresAssignment_2() { return cProfesoresAssignment_2; }

		//[Profesor]
		public CrossReference getProfesoresProfesorCrossReference_2_0() { return cProfesoresProfesorCrossReference_2_0; }

		//ID
		public RuleCall getProfesoresProfesorIDTerminalRuleCall_2_0_1() { return cProfesoresProfesorIDTerminalRuleCall_2_0_1; }

		//"se dicta:"
		public Keyword getSeDictaKeyword_3() { return cSeDictaKeyword_3; }

		//aulaHorarios+=AulaHorario+
		public Assignment getAulaHorariosAssignment_4() { return cAulaHorariosAssignment_4; }

		//AulaHorario
		public RuleCall getAulaHorariosAulaHorarioParserRuleCall_4_0() { return cAulaHorariosAulaHorarioParserRuleCall_4_0; }
	}

	public class AulaHorarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AulaHorario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLosKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDiaAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDiaDiaParserRuleCall_1_0 = (RuleCall)cDiaAssignment_1.eContents().get(0);
		private final Keyword cEnElHorarioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cHorarioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cHorarioHorarioParserRuleCall_3_0 = (RuleCall)cHorarioAssignment_3.eContents().get(0);
		private final Keyword cEnKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAulaAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAulaAulaParserRuleCall_5_0 = (RuleCall)cAulaAssignment_5.eContents().get(0);
		
		//AulaHorario:
		//	"los" dia=Dia "en el horario" horario=Horario "en" aula=Aula;
		public ParserRule getRule() { return rule; }

		//"los" dia=Dia "en el horario" horario=Horario "en" aula=Aula
		public Group getGroup() { return cGroup; }

		//"los"
		public Keyword getLosKeyword_0() { return cLosKeyword_0; }

		//dia=Dia
		public Assignment getDiaAssignment_1() { return cDiaAssignment_1; }

		//Dia
		public RuleCall getDiaDiaParserRuleCall_1_0() { return cDiaDiaParserRuleCall_1_0; }

		//"en el horario"
		public Keyword getEnElHorarioKeyword_2() { return cEnElHorarioKeyword_2; }

		//horario=Horario
		public Assignment getHorarioAssignment_3() { return cHorarioAssignment_3; }

		//Horario
		public RuleCall getHorarioHorarioParserRuleCall_3_0() { return cHorarioHorarioParserRuleCall_3_0; }

		//"en"
		public Keyword getEnKeyword_4() { return cEnKeyword_4; }

		//aula=Aula
		public Assignment getAulaAssignment_5() { return cAulaAssignment_5; }

		//Aula
		public RuleCall getAulaAulaParserRuleCall_5_0() { return cAulaAulaParserRuleCall_5_0; }
	}

	public class PlanificacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Planificacion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlanificacionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSemestreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSemestreSemestreParserRuleCall_1_0 = (RuleCall)cSemestreAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cAsignacionesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAsignacionesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAsignacionesAsignacionParserRuleCall_4_0 = (RuleCall)cAsignacionesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Planificacion:
		//	"planificacion" semestre=Semestre "{" "asignaciones" asignaciones+=Asignacion* "}";
		public ParserRule getRule() { return rule; }

		//"planificacion" semestre=Semestre "{" "asignaciones" asignaciones+=Asignacion* "}"
		public Group getGroup() { return cGroup; }

		//"planificacion"
		public Keyword getPlanificacionKeyword_0() { return cPlanificacionKeyword_0; }

		//semestre=Semestre
		public Assignment getSemestreAssignment_1() { return cSemestreAssignment_1; }

		//Semestre
		public RuleCall getSemestreSemestreParserRuleCall_1_0() { return cSemestreSemestreParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"asignaciones"
		public Keyword getAsignacionesKeyword_3() { return cAsignacionesKeyword_3; }

		//asignaciones+=Asignacion*
		public Assignment getAsignacionesAssignment_4() { return cAsignacionesAssignment_4; }

		//Asignacion
		public RuleCall getAsignacionesAsignacionParserRuleCall_4_0() { return cAsignacionesAsignacionParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class RecursoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Recurso");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRecursoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Recurso:
		//	"recurso" name=ID;
		public ParserRule getRule() { return rule; }

		//"recurso" name=ID
		public Group getGroup() { return cGroup; }

		//"recurso"
		public Keyword getRecursoKeyword_0() { return cRecursoKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	
	
	private ModelElements pModel;
	private ElementosPrimariosElements pElementosPrimarios;
	private ElementosSecundariosElements pElementosSecundarios;
	private ProfesorElements pProfesor;
	private DisponibilidadElements pDisponibilidad;
	private DedicacionElements pDedicacion;
	private MateriaElements pMateria;
	private AulaElements pAula;
	private CargaHorariaElements pCargaHoraria;
	private HorarioElements pHorario;
	private SemestreElements pSemestre;
	private DiaElements pDia;
	private AsignacionElements pAsignacion;
	private AulaHorarioElements pAulaHorario;
	private PlanificacionElements pPlanificacion;
	private RecursoElements pRecurso;
	
	private final Grammar grammar;

	private XbaseGrammarAccess gaXbase;

	@Inject
	public PdmGrammarAccess(GrammarProvider grammarProvider,
		XbaseGrammarAccess gaXbase) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaXbase = gaXbase;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.unq.planificador.Pdm".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public XbaseGrammarAccess getXbaseGrammarAccess() {
		return gaXbase;
	}

	
	//Model:
	//	elementosPrimarios+=ElementosPrimarios elementosSecundarios+=ElementosSecundarios planificacion+=Planificacion;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//ElementosPrimarios:
	//	Profesor | Asignacion | Materia;
	public ElementosPrimariosElements getElementosPrimariosAccess() {
		return (pElementosPrimarios != null) ? pElementosPrimarios : (pElementosPrimarios = new ElementosPrimariosElements());
	}
	
	public ParserRule getElementosPrimariosRule() {
		return getElementosPrimariosAccess().getRule();
	}

	//ElementosSecundarios:
	//	Aula | Recurso;
	public ElementosSecundariosElements getElementosSecundariosAccess() {
		return (pElementosSecundarios != null) ? pElementosSecundarios : (pElementosSecundarios = new ElementosSecundariosElements());
	}
	
	public ParserRule getElementosSecundariosRule() {
		return getElementosSecundariosAccess().getRule();
	}

	//Profesor:
	//	"profesor" name=ID "dedicacion" dedicacion=Dedicacion ("disponibilidad" disponibilidad=Disponibilidad)?;
	public ProfesorElements getProfesorAccess() {
		return (pProfesor != null) ? pProfesor : (pProfesor = new ProfesorElements());
	}
	
	public ParserRule getProfesorRule() {
		return getProfesorAccess().getRule();
	}

	//Disponibilidad:
	//	("no puede" dias+=Dia*)? ("puede" dias+=Dia* "de" inicio=INT "a" fin=INT);
	public DisponibilidadElements getDisponibilidadAccess() {
		return (pDisponibilidad != null) ? pDisponibilidad : (pDisponibilidad = new DisponibilidadElements());
	}
	
	public ParserRule getDisponibilidadRule() {
		return getDisponibilidadAccess().getRule();
	}

	//Dedicacion:
	//	{SIMPLE} "Simple" | {SEMI} "Semi" | {EXCLUSIVA} "Exclusiva";
	public DedicacionElements getDedicacionAccess() {
		return (pDedicacion != null) ? pDedicacion : (pDedicacion = new DedicacionElements());
	}
	
	public ParserRule getDedicacionRule() {
		return getDedicacionAccess().getRule();
	}

	//Materia:
	//	"materia" name=ID "con" cargaHoraria=CargaHoraria ("requiere:" recursos+=Recurso+)?;
	public MateriaElements getMateriaAccess() {
		return (pMateria != null) ? pMateria : (pMateria = new MateriaElements());
	}
	
	public ParserRule getMateriaRule() {
		return getMateriaAccess().getRule();
	}

	//Aula:
	//	"aula" name=ID ("recurso" recursos+=Recurso)? "capacidad" capacidad=INT;
	public AulaElements getAulaAccess() {
		return (pAula != null) ? pAula : (pAula = new AulaElements());
	}
	
	public ParserRule getAulaRule() {
		return getAulaAccess().getRule();
	}

	//CargaHoraria:
	//	"horasSemanales" cantHoras=INT "cantidadDeDias" diasSemanales=INT;
	public CargaHorariaElements getCargaHorariaAccess() {
		return (pCargaHoraria != null) ? pCargaHoraria : (pCargaHoraria = new CargaHorariaElements());
	}
	
	public ParserRule getCargaHorariaRule() {
		return getCargaHorariaAccess().getRule();
	}

	//Horario:
	//	desde=INT "a" hasta=INT;
	public HorarioElements getHorarioAccess() {
		return (pHorario != null) ? pHorario : (pHorario = new HorarioElements());
	}
	
	public ParserRule getHorarioRule() {
		return getHorarioAccess().getRule();
	}

	//Semestre:
	//	anho=INT "semestre" numero=INT;
	public SemestreElements getSemestreAccess() {
		return (pSemestre != null) ? pSemestre : (pSemestre = new SemestreElements());
	}
	
	public ParserRule getSemestreRule() {
		return getSemestreAccess().getRule();
	}

	//Dia:
	//	{Lunes} "Lunes" | {Martes} "Martes" | {Miercoles} "Miercoles" | {Jueves} "Jueves" | {Viernes} "Viernes" | {Sabado}
	//	"Sabado";
	public DiaElements getDiaAccess() {
		return (pDia != null) ? pDia : (pDia = new DiaElements());
	}
	
	public ParserRule getDiaRule() {
		return getDiaAccess().getRule();
	}

	//Asignacion:
	//	materia=[Materia] "la dicta" profesores+=[Profesor]+ "se dicta:" aulaHorarios+=AulaHorario+;
	public AsignacionElements getAsignacionAccess() {
		return (pAsignacion != null) ? pAsignacion : (pAsignacion = new AsignacionElements());
	}
	
	public ParserRule getAsignacionRule() {
		return getAsignacionAccess().getRule();
	}

	//AulaHorario:
	//	"los" dia=Dia "en el horario" horario=Horario "en" aula=Aula;
	public AulaHorarioElements getAulaHorarioAccess() {
		return (pAulaHorario != null) ? pAulaHorario : (pAulaHorario = new AulaHorarioElements());
	}
	
	public ParserRule getAulaHorarioRule() {
		return getAulaHorarioAccess().getRule();
	}

	//Planificacion:
	//	"planificacion" semestre=Semestre "{" "asignaciones" asignaciones+=Asignacion* "}";
	public PlanificacionElements getPlanificacionAccess() {
		return (pPlanificacion != null) ? pPlanificacion : (pPlanificacion = new PlanificacionElements());
	}
	
	public ParserRule getPlanificacionRule() {
		return getPlanificacionAccess().getRule();
	}

	//Recurso:
	//	"recurso" name=ID;
	public RecursoElements getRecursoAccess() {
		return (pRecurso != null) ? pRecurso : (pRecurso = new RecursoElements());
	}
	
	public ParserRule getRecursoRule() {
		return getRecursoAccess().getRule();
	}

	//XExpression:
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaXbase.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}

	//XAssignment returns XExpression:
	//	{XAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign value=XAssignment | XOrExpression
	//	(=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMultiAssign])
	//	rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaXbase.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}

	//OpSingleAssign:
	//	"=";
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaXbase.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}

	//OpMultiAssign:
	//	"+=" | "-=" | "*=" | "/=" | "%=" | "<" "<" "=" | ">" ">"? ">=";
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaXbase.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}

	//XOrExpression returns XExpression:
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaXbase.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}

	//OpOr:
	//	"||";
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaXbase.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}

	//XAndExpression returns XExpression:
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaXbase.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}

	//OpAnd:
	//	"&&";
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaXbase.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}

	//XEqualityExpression returns XExpression:
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaXbase.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//	"==" | "!=" | "===" | "!==";
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaXbase.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//XRelationalExpression returns XExpression:
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} "instanceof") type=JvmTypeReference | =>
	//	({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaXbase.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}

	//OpCompare:
	//	">=" | "<" "=" | ">" | "<";
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaXbase.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}

	//XOtherOperatorExpression returns XExpression:
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaXbase.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}

	//OpOther:
	//	"->" | "..<" | ">" ".." | ".." | "=>" | ">" (=> (">" ">") | ">") | "<" (=> ("<" "<") | "<" | "=>") | "<>" | "?:";
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaXbase.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}

	//XAdditiveExpression returns XExpression:
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaXbase.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//	"+" | "-";
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaXbase.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//XMultiplicativeExpression returns XExpression:
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaXbase.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//	"*" | "**" | "/" | "%";
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaXbase.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//XUnaryOperation returns XExpression:
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XUnaryOperation | XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaXbase.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}

	//OpUnary:
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaXbase.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}

	//XCastedExpression returns XExpression:
	//	XPostfixOperation (=> ({XCastedExpression.target=current} "as") type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaXbase.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}

	//XPostfixOperation returns XExpression:
	//	XMemberFeatureCall => ({XPostfixOperation.operand=current} feature=[types::JvmIdentifiableElement|OpPostfix])?;
	public XbaseGrammarAccess.XPostfixOperationElements getXPostfixOperationAccess() {
		return gaXbase.getXPostfixOperationAccess();
	}
	
	public ParserRule getXPostfixOperationRule() {
		return getXPostfixOperationAccess().getRule();
	}

	//OpPostfix:
	//	"++" | "--";
	public XbaseGrammarAccess.OpPostfixElements getOpPostfixAccess() {
		return gaXbase.getOpPostfixAccess();
	}
	
	public ParserRule getOpPostfixRule() {
		return getOpPostfixAccess().getRule();
	}

	//XMemberFeatureCall returns XExpression:
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} ("." | explicitStatic?="::")
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign) value=XAssignment | =>
	//	({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." | explicitStatic?="::")) ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?="(" (memberCallArguments+=XShortClosure |
	//	memberCallArguments+=XExpression ("," memberCallArguments+=XExpression)*)? ")")? memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaXbase.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}

	//XPrimaryExpression returns XExpression:
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XSynchronizedExpression | XFeatureCall | XLiteral |
	//	XIfExpression | XForLoopExpression | XBasicForLoopExpression | XWhileExpression | XDoWhileExpression |
	//	XThrowExpression | XReturnExpression | XTryCatchFinallyExpression | XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaXbase.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}

	//XLiteral returns XExpression:
	//	XCollectionLiteral | XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaXbase.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}

	//XCollectionLiteral:
	//	XSetLiteral | XListLiteral;
	public XbaseGrammarAccess.XCollectionLiteralElements getXCollectionLiteralAccess() {
		return gaXbase.getXCollectionLiteralAccess();
	}
	
	public ParserRule getXCollectionLiteralRule() {
		return getXCollectionLiteralAccess().getRule();
	}

	//XSetLiteral:
	//	{XSetLiteral} "#" "{" (elements+=XExpression ("," elements+=XExpression)*)? "}";
	public XbaseGrammarAccess.XSetLiteralElements getXSetLiteralAccess() {
		return gaXbase.getXSetLiteralAccess();
	}
	
	public ParserRule getXSetLiteralRule() {
		return getXSetLiteralAccess().getRule();
	}

	//XListLiteral:
	//	{XListLiteral} "#" "[" (elements+=XExpression ("," elements+=XExpression)*)? "]";
	public XbaseGrammarAccess.XListLiteralElements getXListLiteralAccess() {
		return gaXbase.getXListLiteralAccess();
	}
	
	public ParserRule getXListLiteralRule() {
		return getXListLiteralAccess().getRule();
	}

	//XClosure returns XExpression:
	//	=> ({XClosure} "[") => ((declaredFormalParameters+=JvmFormalParameter (","
	//	declaredFormalParameters+=JvmFormalParameter)*)? explicitSyntax?="|")? expression=XExpressionInClosure "]";
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaXbase.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}

	//XExpressionInClosure returns XExpression:
	//	{XBlockExpression} (expressions+=XExpressionOrVarDeclaration ";"?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaXbase.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}

	//XShortClosure returns XExpression:
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter ("," declaredFormalParameters+=JvmFormalParameter)*)?
	//	explicitSyntax?="|") expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaXbase.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}

	//XParenthesizedExpression returns XExpression:
	//	"(" XExpression ")";
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaXbase.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}

	//XIfExpression returns XExpression:
	//	{XIfExpression} "if" "(" if=XExpression ")" then=XExpression ("else" else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaXbase.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}

	//XSwitchExpression returns XExpression:
	//	{XSwitchExpression} "switch" (=> ("(" declaredParam=JvmFormalParameter ":") switch=XExpression ")" | =>
	//	(declaredParam=JvmFormalParameter ":")? switch=XExpression) "{" cases+=XCasePart* ("default" ":" default=XExpression)?
	//	"}";
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaXbase.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}

	//XCasePart:
	//	{XCasePart} typeGuard=JvmTypeReference? ("case" case=XExpression)? (":" then=XExpression | ",");
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaXbase.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}

	//XForLoopExpression returns XExpression:
	//	=> ({XForLoopExpression} "for" "(" declaredParam=JvmFormalParameter ":") forExpression=XExpression ")"
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaXbase.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}

	//XBasicForLoopExpression returns XExpression:
	//	{XBasicForLoopExpression} "for" "(" (initExpressions+=XExpressionOrVarDeclaration (","
	//	initExpressions+=XExpressionOrVarDeclaration)*)? ";" expression=XExpression? ";" (updateExpressions+=XExpression (","
	//	updateExpressions+=XExpression)*)? ")" eachExpression=XExpression;
	public XbaseGrammarAccess.XBasicForLoopExpressionElements getXBasicForLoopExpressionAccess() {
		return gaXbase.getXBasicForLoopExpressionAccess();
	}
	
	public ParserRule getXBasicForLoopExpressionRule() {
		return getXBasicForLoopExpressionAccess().getRule();
	}

	//XWhileExpression returns XExpression:
	//	{XWhileExpression} "while" "(" predicate=XExpression ")" body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaXbase.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}

	//XDoWhileExpression returns XExpression:
	//	{XDoWhileExpression} "do" body=XExpression "while" "(" predicate=XExpression ")";
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaXbase.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}

	//XBlockExpression returns XExpression:
	//	{XBlockExpression} "{" (expressions+=XExpressionOrVarDeclaration ";"?)* "}";
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaXbase.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}

	//XExpressionOrVarDeclaration returns XExpression:
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionOrVarDeclarationElements getXExpressionOrVarDeclarationAccess() {
		return gaXbase.getXExpressionOrVarDeclarationAccess();
	}
	
	public ParserRule getXExpressionOrVarDeclarationRule() {
		return getXExpressionOrVarDeclarationAccess().getRule();
	}

	//XVariableDeclaration returns XExpression:
	//	{XVariableDeclaration} (writeable?="var" | "val") (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ("="
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaXbase.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaXbase.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//FullJvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaXbase.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}

	//XFeatureCall returns XExpression:
	//	{XFeatureCall} ("<" typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?="(" (featureCallArguments+=XShortClosure
	//	| featureCallArguments+=XExpression ("," featureCallArguments+=XExpression)*)? ")")? featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaXbase.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}

	//FeatureCallID:
	//	ValidID | "extends" | "static" | "import" | "extension";
	public XbaseGrammarAccess.FeatureCallIDElements getFeatureCallIDAccess() {
		return gaXbase.getFeatureCallIDAccess();
	}
	
	public ParserRule getFeatureCallIDRule() {
		return getFeatureCallIDAccess().getRule();
	}

	//IdOrSuper:
	//	FeatureCallID | "super";
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaXbase.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}

	//XConstructorCall returns XExpression:
	//	{XConstructorCall} "new" constructor=[types::JvmConstructor|QualifiedName] ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")? (=>
	//	explicitConstructorCall?="(" (arguments+=XShortClosure | arguments+=XExpression ("," arguments+=XExpression)*)? ")")?
	//	arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaXbase.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}

	//XBooleanLiteral returns XExpression:
	//	{XBooleanLiteral} ("false" | isTrue?="true");
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaXbase.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}

	//XNullLiteral returns XExpression:
	//	{XNullLiteral} "null";
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaXbase.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}

	//XNumberLiteral returns XExpression:
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaXbase.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}

	//XStringLiteral returns XExpression:
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaXbase.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}

	//XTypeLiteral returns XExpression:
	//	{XTypeLiteral} "typeof" "(" type=[types::JvmType|QualifiedName] arrayDimensions+=ArrayBrackets* ")";
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaXbase.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}

	//XThrowExpression returns XExpression:
	//	{XThrowExpression} "throw" expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaXbase.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}

	//XReturnExpression returns XExpression:
	//	{XReturnExpression} "return" -> expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaXbase.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}

	//XTryCatchFinallyExpression returns XExpression:
	//	{XTryCatchFinallyExpression} "try" expression=XExpression (catchClauses+=XCatchClause+ ("finally"
	//	finallyExpression=XExpression)? | "finally" finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaXbase.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}

	//XSynchronizedExpression returns XExpression:
	//	=> ({XSynchronizedExpression} "synchronized" "(") param=XExpression ")" expression=XExpression;
	public XbaseGrammarAccess.XSynchronizedExpressionElements getXSynchronizedExpressionAccess() {
		return gaXbase.getXSynchronizedExpressionAccess();
	}
	
	public ParserRule getXSynchronizedExpressionRule() {
		return getXSynchronizedExpressionAccess().getRule();
	}

	//XCatchClause:
	//	"catch" "(" declaredParam=FullJvmFormalParameter ")" expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaXbase.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}

	//QualifiedName:
	//	ValidID ("." ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Number hidden():
	//	HEX | (INT | DECIMAL) ("." (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaXbase.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	/// **
	// * Dummy rule, for "better" downwards compatibility, since GrammarAccess generates non-static inner classes, 
	// * which makes downstream grammars break on classloading, when a rule is removed.
	// * / StaticQualifier:
	//	(ValidID "::")+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaXbase.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}

	//terminal HEX:
	//	("0x" | "0X") ("0".."9" | "a".."f" | "A".."F" | "_")+ ("#" (("b" | "B") ("i" | "I") | ("l" | "L")))?;
	public TerminalRule getHEXRule() {
		return gaXbase.getHEXRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9" ("0".."9" | "_")*;
	public TerminalRule getINTRule() {
		return gaXbase.getINTRule();
	} 

	//terminal DECIMAL:
	//	INT (("e" | "E") ("+" | "-")? INT)? (("b" | "B") ("i" | "I" | "d" | "D") | ("l" | "L" | "d" | "D" | "f" | "F"))?;
	public TerminalRule getDECIMALRule() {
		return gaXbase.getDECIMALRule();
	} 

	//JvmTypeReference:
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} ArrayBrackets)* |
	//	XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaXbase.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//ArrayBrackets:
	//	"[" "]";
	public XtypeGrammarAccess.ArrayBracketsElements getArrayBracketsAccess() {
		return gaXbase.getArrayBracketsAccess();
	}
	
	public ParserRule getArrayBracketsRule() {
		return getArrayBracketsAccess().getRule();
	}

	//XFunctionTypeRef:
	//	("(" (paramTypes+=JvmTypeReference ("," paramTypes+=JvmTypeReference)*)? ")")? "=>" returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaXbase.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}

	//JvmParameterizedTypeReference:
	//	type=[JvmType|QualifiedName] ("<" arguments+=JvmArgumentTypeReference ("," arguments+=JvmArgumentTypeReference)*
	//	">")?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaXbase.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}

	//JvmArgumentTypeReference returns JvmTypeReference:
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaXbase.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}

	//JvmWildcardTypeReference:
	//	{JvmWildcardTypeReference} "?" (constraints+=JvmUpperBound | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaXbase.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}

	//JvmUpperBound:
	//	"extends" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaXbase.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}

	//JvmUpperBoundAnded returns JvmUpperBound:
	//	"&" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaXbase.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}

	//JvmLowerBound:
	//	"super" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaXbase.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}

	//JvmTypeParameter:
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded*)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaXbase.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}

	//QualifiedNameWithWildcard:
	//	QualifiedName "." "*";
	public XtypeGrammarAccess.QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return gaXbase.getQualifiedNameWithWildcardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//ValidID:
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaXbase.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//XImportSection:
	//	importDeclarations+=XImportDeclaration+;
	public XtypeGrammarAccess.XImportSectionElements getXImportSectionAccess() {
		return gaXbase.getXImportSectionAccess();
	}
	
	public ParserRule getXImportSectionRule() {
		return getXImportSectionAccess().getRule();
	}

	//XImportDeclaration:
	//	"import" (static?="static" extension?="extension"? importedType=[JvmDeclaredType|QualifiedNameInStaticImport]
	//	(wildcard?="*" | memberName=ValidID) | importedType=[JvmDeclaredType|QualifiedName] |
	//	importedNamespace=QualifiedNameWithWildcard) ";"?;
	public XtypeGrammarAccess.XImportDeclarationElements getXImportDeclarationAccess() {
		return gaXbase.getXImportDeclarationAccess();
	}
	
	public ParserRule getXImportDeclarationRule() {
		return getXImportDeclarationAccess().getRule();
	}

	//QualifiedNameInStaticImport:
	//	(ValidID ".")+;
	public XtypeGrammarAccess.QualifiedNameInStaticImportElements getQualifiedNameInStaticImportAccess() {
		return gaXbase.getQualifiedNameInStaticImportAccess();
	}
	
	public ParserRule getQualifiedNameInStaticImportRule() {
		return getQualifiedNameInStaticImportAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "$" | "_") ("a".."z" | "A".."Z" | "$" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaXbase.getIDRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaXbase.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaXbase.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaXbase.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaXbase.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaXbase.getANY_OTHERRule();
	} 
}
