/*
* generated by Xtext
*/
package org.xtext.unq.planificador.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.unq.planificador.services.PdmGrammarAccess;

public class PdmParser extends AbstractContentAssistParser {
	
	@Inject
	private PdmGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.unq.planificador.ui.contentassist.antlr.internal.InternalPdmParser createParser() {
		org.xtext.unq.planificador.ui.contentassist.antlr.internal.InternalPdmParser result = new org.xtext.unq.planificador.ui.contentassist.antlr.internal.InternalPdmParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDedicacionAccess().getAlternatives(), "rule__Dedicacion__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getProfesorAccess().getGroup(), "rule__Profesor__Group__0");
					put(grammarAccess.getHoraAccess().getGroup(), "rule__Hora__Group__0");
					put(grammarAccess.getMateriaAccess().getGroup(), "rule__Materia__Group__0");
					put(grammarAccess.getAulaAccess().getGroup(), "rule__Aula__Group__0");
					put(grammarAccess.getCargaHorariaAccess().getGroup(), "rule__CargaHoraria__Group__0");
					put(grammarAccess.getCargaHorariaDocenteAccess().getGroup(), "rule__CargaHorariaDocente__Group__0");
					put(grammarAccess.getHorarioAccess().getGroup(), "rule__Horario__Group__0");
					put(grammarAccess.getSemestreAccess().getGroup(), "rule__Semestre__Group__0");
					put(grammarAccess.getDiaAccess().getGroup(), "rule__Dia__Group__0");
					put(grammarAccess.getHorariosAccess().getGroup(), "rule__Horarios__Group__0");
					put(grammarAccess.getPlanificacionAccess().getGroup(), "rule__Planificacion__Group__0");
					put(grammarAccess.getModelAccess().getProfesorsAssignment_0(), "rule__Model__ProfesorsAssignment_0");
					put(grammarAccess.getModelAccess().getHorasAssignment_1(), "rule__Model__HorasAssignment_1");
					put(grammarAccess.getModelAccess().getMateriasAssignment_2(), "rule__Model__MateriasAssignment_2");
					put(grammarAccess.getModelAccess().getAulasAssignment_3(), "rule__Model__AulasAssignment_3");
					put(grammarAccess.getModelAccess().getCargasHorariasAssignment_4(), "rule__Model__CargasHorariasAssignment_4");
					put(grammarAccess.getModelAccess().getCargasHorariasDocentesAssignment_5(), "rule__Model__CargasHorariasDocentesAssignment_5");
					put(grammarAccess.getModelAccess().getHorariosAssignment_6(), "rule__Model__HorariosAssignment_6");
					put(grammarAccess.getModelAccess().getDiasAssignment_7(), "rule__Model__DiasAssignment_7");
					put(grammarAccess.getModelAccess().getSemestreAssignment_8(), "rule__Model__SemestreAssignment_8");
					put(grammarAccess.getModelAccess().getPlanificacionesAssignment_9(), "rule__Model__PlanificacionesAssignment_9");
					put(grammarAccess.getModelAccess().getHorariosAssignment_10(), "rule__Model__HorariosAssignment_10");
					put(grammarAccess.getProfesorAccess().getNombreAssignment_1(), "rule__Profesor__NombreAssignment_1");
					put(grammarAccess.getProfesorAccess().getDedicacionAssignment_3(), "rule__Profesor__DedicacionAssignment_3");
					put(grammarAccess.getHoraAccess().getHoraAssignment_1(), "rule__Hora__HoraAssignment_1");
					put(grammarAccess.getMateriaAccess().getNombreAssignment_1(), "rule__Materia__NombreAssignment_1");
					put(grammarAccess.getMateriaAccess().getCargaHorariaAssignment_3(), "rule__Materia__CargaHorariaAssignment_3");
					put(grammarAccess.getAulaAccess().getNombreAssignment_1(), "rule__Aula__NombreAssignment_1");
					put(grammarAccess.getCargaHorariaAccess().getTipoAssignment_1(), "rule__CargaHoraria__TipoAssignment_1");
					put(grammarAccess.getCargaHorariaAccess().getDiasAssignment_3(), "rule__CargaHoraria__DiasAssignment_3");
					put(grammarAccess.getCargaHorariaDocenteAccess().getNombreAssignment_0(), "rule__CargaHorariaDocente__NombreAssignment_0");
					put(grammarAccess.getCargaHorariaDocenteAccess().getTipoAssignment_2(), "rule__CargaHorariaDocente__TipoAssignment_2");
					put(grammarAccess.getHorarioAccess().getDiaAssignment_0(), "rule__Horario__DiaAssignment_0");
					put(grammarAccess.getHorarioAccess().getDesdeAssignment_2(), "rule__Horario__DesdeAssignment_2");
					put(grammarAccess.getHorarioAccess().getHastaAssignment_4(), "rule__Horario__HastaAssignment_4");
					put(grammarAccess.getHorarioAccess().getMateriaAssignment_6(), "rule__Horario__MateriaAssignment_6");
					put(grammarAccess.getHorarioAccess().getAulaAssignment_8(), "rule__Horario__AulaAssignment_8");
					put(grammarAccess.getSemestreAccess().getAnhoAssignment_0(), "rule__Semestre__AnhoAssignment_0");
					put(grammarAccess.getSemestreAccess().getNumeroAssignment_2(), "rule__Semestre__NumeroAssignment_2");
					put(grammarAccess.getDiaAccess().getDiaAssignment_1(), "rule__Dia__DiaAssignment_1");
					put(grammarAccess.getHorariosAccess().getHorariosAssignment_1(), "rule__Horarios__HorariosAssignment_1");
					put(grammarAccess.getPlanificacionAccess().getSemestreAssignment_1(), "rule__Planificacion__SemestreAssignment_1");
					put(grammarAccess.getPlanificacionAccess().getMateriasAssignment_4(), "rule__Planificacion__MateriasAssignment_4");
					put(grammarAccess.getPlanificacionAccess().getHorariosAssignment_5(), "rule__Planificacion__HorariosAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.unq.planificador.ui.contentassist.antlr.internal.InternalPdmParser typedParser = (org.xtext.unq.planificador.ui.contentassist.antlr.internal.InternalPdmParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PdmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PdmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
