/*
 * generated by Xtext
 */
package org.xtext.unq.planificador;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PdmRuntimeModule extends org.xtext.unq.planificador.AbstractPdmRuntimeModule {

}
