/*
* generated by Xtext
*/
package org.xtext.unq.planificador;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PdmStandaloneSetup extends PdmStandaloneSetupGenerated{

	public static void doSetup() {
		new PdmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

