/*
* generated by Xtext
*/
package org.xtext.unq.planificador;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PdmUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.unq.planificador.ui.internal.PdmActivator.getInstance().getInjector("org.xtext.unq.planificador.Pdm");
	}
	
}
