/*
 * generated by Xtext
 */
package org.xtext.unq.planificador.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PdmUiModule extends org.xtext.unq.planificador.ui.AbstractPdmUiModule {
	public PdmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
