/*
* generated by Xtext
*/
package org.xtext.unq.planificador.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.unq.planificador.services.PdmGrammarAccess;

public class PdmParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PdmGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.unq.planificador.parser.antlr.internal.InternalPdmParser createParser(XtextTokenStream stream) {
		return new org.xtext.unq.planificador.parser.antlr.internal.InternalPdmParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PdmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PdmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
